### ISSUE TITLE
Rewriting parm file

### ISSUE THREAD

**Issue by Steboss** [ParmEd/ParmEd#547] opened 2016-01-15 16:06 UTC
Hi

I was rewriting a parm file, to have a different name for a residue, as:

```
from chemistry.amber import *


base = AmberParm(top,crd)
name = base.residues[2].name
for res in base.residues:
    if name in res.name:
        res.name = "XXX"
    else:
        continue

base.remake_parm()
base.write_parm(new_top)
```

Once everything is done the new topology does not contain the flag for box dimensions
where did I go wrong?

Thank you,

Stefano

**Comment by swails** [comment] 2016-01-15 17:41
This is a defect in older versions of ParmEd (which you are clearly using since the main package name was changed to parmed some time ago from chemistry. 

There is a historical explanation for why ParmEd would get rid of the box on topology files. Originally the main use for remake_parm was to strip solvent for use in MM/PBSA applications, so if it didn't detect water in the residue list, ParmEd would get rid of the box information. But this turned out to be more of a problem than a help, so the behavior was recently changed.

So to fix this, update to the latest version of ParmEd and change the import from chemistry to parmed. 

Also you shouldn't have to call remake_parm anymore, as ParmEd does this automatically when it writes a prmtop.

**Comment by hainm** [comment] 2016-01-15 17:42
like this

```python
In [32]: import parmed as pmd

In [33]: base = pmd.load_file('tz2.ortho.parm7')

In [34]: base.box
Out[34]: array([ 39.455974,  46.821517,  40.469541,  90.    ,  90.      ,  90.      ])

In [35]: name = base.residues[2].name

In [36]: name
Out[36]: 'THR'

In [37]: for res in base.residues:
   ....:     if name in res.name:
   ....:         res.name = 'XXX'
   ....:         

In [40]: new_top = pmd.load_file('new_prmtop.parm7')

In [41]: new_top.box
Out[41]: array([ 39.455974,  46.821517,  40.469541,  90.    ,  90.      ,  90.      ])
```

**Comment by Steboss** [comment] 2016-01-22 11:22
Thank for your help
Unfortunately even if I have updated parmed version I cannot save box dimensions yet

my code is like:
```
import parmed as pmd
base = pmd.load_file("topology")

..modification...

base.save("new_topology")
```


in the new_topology file I don't have box dimension yet

Where am I wrong?

**Comment by Steboss** [comment] 2016-01-22 12:21
Ok, I think the problem I have is  what topology save as output

If I do:
``` base = pmd.amber.AmberParm("TOP","CRD")
    base.save("NEWTOP.top")
```

a GROMACS topology is save ( I think it's GROMACS format) with correct box information
but if I do:

``` base.save("NEWTOP.parm7",format="amber")
```
or
``` base.save("NEWTOP.parm7")
```
an AMBER topology is saved, but without box flag

**Comment by swails** [comment] 2016-01-22 13:16
If you look at the [documentation of the `Structure.save` function](http://parmed.github.io/ParmEd/html/readwrite.html#writing-files-with-structure-save) you'll see what suffixes correspond with which file formats.

The GROMACS topology file format does not contain unit cell information.

The Amber topology file, however, *does* contain unit cell information.  There are a couple ways that you can wind up discarding unit cell information, but none of that should happen by default anymore.  So if the system box is being lost somewhere, that's occurring in the section of the code you are omitting from your posts.

I would need to see the entire script you are using to determine where the unit cell information is lost.  (Obviously, though, you should check that `"TOP"` and `"CRD"` have box dimensions to start with -- if there are no unit cell dimensions in the beginning, there won't be any at the end).

Another possibility is that the CRD unit cell information is overwriting the TOP unit cell information (since Amber ignores the box dimensions in the prmtop and *only* uses what is in the coordinate file, ParmEd does the same thing).  So if your TOP has box info, but your CRD does not, then using the command `base = pmd.amber.AmberParm('TOP', 'CRD')` will wind up with a system having no box.

**Comment by Steboss** [comment] 2016-01-22 13:28
Actually the script above was just an example
at the moment I'm trying to see if box information are correctly passed if I am saving a new file
Therefore I am simply running this:
```
base = pmd.amber.AmberParm("TOP","CRD")
base.write_parm("NEWTOP")
```
If I examine the new topology I am missing not only the box information (%FLAG BOX_DIMENSION) but also: %FLAG SOLVENT POINTERS  and %FLAG ATOMS PER MOLECULE

The topology has box information at the last line

I have try also 
```
base = pmd.load_file("TOPOLOGY")

base.save("NEWTOPOLOGY")
```
but nothing to do I dont have the box flag

**Comment by swails** [comment] 2016-01-22 13:41
Then at this point I'm going to need the files you are trying this on so I can try to reproduce it, because this should not be happening.

**Comment by Steboss** [comment] 2016-01-22 13:47
Thanks for the help
Here the topolgy and coordinate files

[topoloy.zip](https://github.com/ParmEd/ParmEd/files/100837/topoloy.zip)

**Comment by swails** [comment] 2016-01-22 14:03
I can't reproduce what you're seeing:

```Python
In [1]: import parmed as pmd

In [2]: parm = pmd.load_file('SYSTEM.prmtop', 'SYSTEM.rst7')

In [3]: parm.box
Out[3]: array([ 45.491,  45.441,  45.463,  90.   ,  90.   ,  90.   ])

In [4]: parm.save('test.parm7')

In [5]: parm2 = pmd.load_file('test.parm7')

In [6]: parm2.box
Out[6]: array([ 45.491,  45.441,  45.463,  90.   ,  90.   ,  90.   ])

In [7]: pmd.version
Out[7]: version(major=2, minor=1, patchlevel=4)
```

If I diff `test.parm7` and `SYSTEM.prmtop` (ignoring whitespace differences), the only diff I get is the version:

```
bash $ diff -w test.parm7 SYSTEM.prmtop 
1c1
< %VERSION  VERSION_STAMP = V0001.000  DATE = 01/22/16  08:55:11
---
> %VERSION  VERSION_STAMP = V0001.000  DATE = 10/07/15  13:19:13                  
```

You *must* not be using an up-to-date ParmEd.  As you can see, the version I have installed is 2.1.4.  This bug was fixed in #489, and from that commit you can tell that you need at *least* ParmEd version 2.0.10 for this to work.

**Comment by Steboss** [comment] 2016-01-22 14:09
OK!

There must be something wrong on my workstation with parmed  version

Thank you very much for your help!

Stefano

**Comment by swails** [comment] 2016-01-22 14:21
No problem.  You can always check your ParmEd version via

```Python
import parmed
print(parmed.__version__)
# or
print(parmed.version)
```

The latter (`parmed.version`) is a tuple of integers you can use to quickly and easily impose version limits on ParmEd in your script.  So you know that version 2.0.10 is needed to avoid deleting the box in an Amber prmtop, so just put this in your script:

```Python
import parmed as pmd

# Check version
if pmd.version < (2, 0, 10):
    raise ImportError('ParmEd version 2.0.10 or later is needed. You have %s' % pmd.__version__)
```

**Comment by swails** [comment] 2016-01-22 14:22
I'm going to go ahead and close this, since it's already fixed (or I just can't reproduce it).  Feel free to reopen if you have a case I can repro.

**Closed by swails** 2016-01-22 14:22 UTC
