### ISSUE TITLE
ParmEd 3 finds many more periodic impropers than 2.7 (and misses some)

### ISSUE THREAD

**Issue by stefdoerr** [ParmEd/ParmEd#990] opened 2018-06-14 14:22 UTC
Here is the file to test 
[structure.zip](https://github.com/ParmEd/ParmEd/files/2102687/structure.zip)

```python
import parmed
x = parmed.load_file('structure.prmtop')
prm = parmed.amber.AmberParameterSet.from_structure(x)
```
Checking in parmed 2.7
```
In [6]: prm.improper_types
Out[6]: OrderedDict()
In [7]: prm.improper_periodic_types
Out[7]: 
OrderedDict([(('ca', 'ca', 'ca', 'cl'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'ca', 'ca', 'ca'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'ns', 'za', 'zb'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'zc', 'za', 'zb'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'zc', 'c3', 'za'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ca', 'ca', 'ca', 'ha'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('za', 'c3', 'ns', 'hn'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>)])
```
Checking in parmed 3
```
In [4]: prm.improper_types
Out[4]: OrderedDict()
In [5]: prm.improper_periodic_types
Out[5]: 
OrderedDict([(('ca', 'ca', 'ca', 'cl'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ca', 'cl', 'ca', 'ca'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('cl', 'ca', 'ca', 'ca'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ca', 'c3', 'ca', 'ca'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ca', 'ca', 'ca', 'c3'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'ca', 'ca', 'ca'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('zb', 'c3', 'za', 'ns'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('zb', 'ns', 'za', 'c3'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'zb', 'za', 'ns'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'ns', 'za', 'zb'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ns', 'zb', 'za', 'c3'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ns', 'c3', 'za', 'zb'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'zb', 'za', 'zc'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'zc', 'za', 'zb'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('zb', 'c3', 'za', 'zc'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('zb', 'zc', 'za', 'c3'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('zc', 'c3', 'za', 'zb'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('zc', 'zb', 'za', 'c3'),
              <DihedralType; phi_k=10.500, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'za', 'zc', 'c3'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'c3', 'zc', 'za'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('za', 'c3', 'zc', 'c3'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ca', 'ha', 'ca', 'ca'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ca', 'ca', 'ca', 'ha'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('ha', 'ca', 'ca', 'ca'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('hn', 'za', 'ns', 'c3'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('hn', 'c3', 'ns', 'za'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('za', 'hn', 'ns', 'c3'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('za', 'c3', 'ns', 'hn'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'hn', 'ns', 'za'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>),
             (('c3', 'za', 'ns', 'hn'),
              <DihedralType; phi_k=1.100, per=2, phase=180.000,  scee=0.000, scnb=0.000>)])
```

In parmed3 it's missing (or has reordered) the `('c3', 'zc', 'c3', 'za')` improper which it has in parmed2.

**Comment by swails** [comment] 2018-06-14 14:54
There was a pretty hefty overhaul of how ParmEd handled/recognized/treated improper torsions (easily the hardest and most annoying part of force field translations/conversions to get right).

Every program has their own conventions (and they often don't share a functional form).  Amber's convention is to put the "central" atom 3rd -- the others are typically stored in alphabetical order in the parameter files.  So for instance, you'll never actually *see* `('c3', 'zc', 'c3', 'za')` in an Amber frcmod/parm file -- it'll be `('c3', 'za', 'c3', 'zc')` (since `za` comes before `zc` alphabetically).

However, in some rare occurrences, Amber doesn't put the central atom third (for instance if the third atom in a torsion happens to be the first atom in the system, then its index in these dihedral arrays is 0, which can't be made negative to indicate the torsion's end-groups should be ignored, so it must be reversed).

The change in strategy that results in what you're seeing here is that ParmEd 3 uses the bonds to actually *find* the central atom (instead of assuming it's in the third position), and then enumerates every possible permutation of the remaining three atoms.

If the problem of impropers is a nail, this approach is like hitting it with a 10kg sledgehammer.  It shouldn't be necessary to do all of that, but it should also never fail (and always be correct).  And after missing the nail so many times with so many smaller hammers, an oversized sledgehammer starts to look pretty attractive :wink:

The real question is "which parameter set can print a frcmod file that correctly parametrizes the system again"?

**Comment by stefdoerr** [comment] 2018-06-14 20:48
Well but `('c3', 'za', 'c3', 'zc')` doesn't exist either in parmed3. I only see `('c3', 'za', 'zc', 'c3'), (('c3', 'c3', 'zc', 'za'), ('za', 'c3', 'zc', 'c3')` so I assume it detected the `zc` as the central atom. My problem is though that I read the `prmtop` myself and it has improper indexes which give me `('c3', 'zc', 'c3', 'za')`. I cannot try all permutations as I might get the wrong parameters if I swap the central atom out. So I guess I will need to write a similar function that checks the bonds to detect the central atom.

By the way, wouldn't it make more sense in that case to overload the `__getitem__/__getattr__` method to check all possible combinations, or add a `getImproper()` method instead of copying the parameters in the list for every possible key combination? To make the sledgehammer a bit more elegant? :stuck_out_tongue: 
Because I think this will complicate other code using parmed a decent bit if it doesn't acknowledge that there are copies of the parameters.

**Comment by stefdoerr** [comment] 2018-06-15 12:00
About the center atom it seems like you are right, the last one is a 0 which is not in column 3
```python
In [18]: [detectImproperCenter(mol.impropers[i], g) for i in range(mol.impropers.shape[0])]
Out[18]: [25, 24, 22, 21, 20, 19, 18, 17, 16, 8, 23, 15, 14, 4, 2, 0]

In [19]: mol.impropers
Out[19]: 
array([[15, 23, 25, 50],
       [14, 22, 24, 49],
       [20, 24, 22, 47],
       [19, 23, 21, 51],
       [18, 22, 20, 46],
       [17, 21, 19, 45],
       [16, 20, 18, 44],
       [15, 19, 17, 43],
       [14, 18, 16, 42],
       [ 4, 12,  8, 30],
       [21, 25, 23, 48],
       [12, 17, 15, 25],
       [11, 16, 14, 24],
       [ 1,  8,  4,  5],
       [ 7,  0,  2,  3],
       [13,  0,  1,  2]], dtype=uint32)
```

**Comment by swails** [comment] 2018-06-15 15:33
> About the center atom it seems like you are right, the last one is a 0 which is not in column 3

This happened a lot more frequently than I expected it to (rather naively, I might add).

As for the atom center algorithm ParmEd uses, [you can find it here](https://github.com/ParmEd/ParmEd/blob/3.0.3/parmed/parameters.py#L464-L481)

That function looks through the bonds, finds the one atom that has a bond to all others.  The logic is a little tricky (mainly due to my use of the `for ... else` construct), but for each atom in the improper, it looks through every *other* atom in the improper and checks if it's in the first atom's bond partner list.  If any are not found, it breaks out of the loop and tries the next atom.  If every other atom is in the first atom's bond list, it hits the `else` clause and then proceeds to yield every possible permutation of the 3 non-central atoms (using the built-in `collections.permutations`) with the identified central atom in position 3.

If none of the atoms appear to be "central" from the bond partners, it falls back on the assumption that it's positioned in the 3rd spot.

> By the way, wouldn't it make more sense in that case to overload the __getitem__/__getattr__ method to check all possible combinations, or add a getImproper() method instead of copying the parameters in the list for every possible key combination? To make the sledgehammer a bit more elegant?

I've since had to add a method like `getImproper` so that the parameter set can remember the order that it read in, so it might be a good idea to move that change here.  My main concern was that tleap wouldn't find an improper it should...  So it would require a good deal of testing before trimming down the current list.

It looks like the "new" behavior is more correct, for what that's worth.  Is that your understanding as well?

**Comment by swails** [comment] 2018-06-15 15:34
Also, you can open a new issue for `get_improper` so it doesn't get lost in this issue.

**Comment by slochower** [comment] 2018-06-16 19:20
I may be derailing this issue (sorry!), but I'd like to interject and assert my ignorance about something that maybe you can clear up easily and quickly (and might have value for others). What is the difference between `AmberParm` and `AmberParameterSet`, specifically with respect to impropers? 

If I load in an Amber `prmtop` file with or without `structure = True`, I get an `AmberParm` object. If I query that for impropers, I get nothing (an empty `TrackedList`). However, I can loop over the dihedrals and use `dihedral.improper` to check whether the dihedral is an improper. Previously, I was mistakenly thinking `AmberParm.dihedrals` were all the proper dihedrals and `AmberParm.impropers` were the impropers. (And I was using some structures with no impropers, so I wasn't worried when `AmberParm.impropers` was empty). 

But reading this thread made me try using `pmd.amber.AmberParameterSet.from_structure(AmberParm)`. Now I can loop over the impropers, which is good, but I realized I don't know the difference between the  `AmberParameterSet` and the `AmberParm`. In general, if I want access to the parameters for a system, should I always go through `AmberParameterSet`?

Sorry, again, for the digression, but I thought this might be useful here because @stefdoerr starts by going from a structure to an `AmberParameterSet` in the first post.

**Comment by swails** [comment] 2018-06-16 23:19
`AmberParm` is a subclass of `Structure` that mirrors the data in a prmtop file.  It contains atoms, bonds, angles, dihedrals, and all of their parameters:

* `parm.atoms`
* `parm.bonds`
* `parm.angles`
* `parm.urey_bradleys` (ChamberParm only)
* `parm.dihedrals`
* `parm.impropers` (ChamberParm only) -- these are not exactly what you think
* `parm.cmaps` (ChamberParm only)
* `parm.atom_types`
* `parm.bond_types`
* `parm.angle_types`
* `parm.urey_bradley_types` (ChamberParm only)
* `parm.dihedral_types`
* `parm.improper_types`
* `parm.cmap_types`

These are all `TrackedList` instances.  The XYZType instances defining the parameter types for each atom, bond, angle, dihedral, etc. are stored in the xyz_type arrays.  They get their indexes from those arrays, which are used to populate the pointer sections of the prmtop file.

By contrast, `AmberParameterSet` inherits from `ParameterSet`.  It contains no atoms or molecular topology at all -- just a mapping of atom types to parameters.  It has all of the `xyz_type` attributes, but rather than being `TrackedList` instances they are dictionaries in which the keys are the atom type name tuples assigned to those atom types and the values are the `XYZType`s for that particular term in the force field.

If you are familiar with the Amber parlance, `AmberParm` == a prmtop file.  `AmberParameterSet` == a frcmod file.

> However, I can loop over the dihedrals and use dihedral.improper to check whether the dihedral is an improper. Previously, I was mistakenly thinking AmberParm.dihedrals were all the proper dihedrals and AmberParm.impropers were the impropers. (And I was using some structures with no impropers, so I wasn't worried when AmberParm.impropers was empty).

These terms are really misnomers, and is a result of how ParmEd evolved organically from a set of parsers I wrote for Amber files into the more general-purpose, multi-program set of data structures it is today.  Amber uses the same functional form -- a Fourier series -- to model both proper and improper torsions.  The only difference between them is how they are assigned by tleap.  But in the prmtop file they're all in the same list.  Which is why all torsions -- proper and improper -- were packed into the same `dihedral` array.

However, while CHARMM uses the same functional form as Amber for proper torsions, it uses a quadratic form for improper torsions.  And these are stored in a separate "improper" section of the chamber-style prmtop file.  So I packed these into a new "improper" list in the `AmberParm` instance.

So think of `Structure.dihedrals` as the list of all 4-atom terms using the standard Fourier proper torsion functional form -- this includes most standard proper torsions *and* Amber-style improper torsions (with, as you noticed, an `improper` flag on each `Dihedral` to indicate what kind of Fourier-functional torsion it is).  `Structure.impropers` is the list of all 4-atom terms using a quadratic torsional functional form (which are *only* CHARMM-style improper torsions).

------------

And now we get to `AmberParameterSet` (and `ParameterSet`) -- these data structures were added way after I learned from (some of) my mistakes building `AmberParm` (which was later abstracted to `Structure` to facilitate supporting additional programs and force fields).  So I added separate lookup tables for periodic improper, quadratic improper, and proper torsion parameters.

The `ParameterSet.from_structure` constructor will basically construct the atom type - parameter type maps from all of the parameters in that `Structure`.

This was long-winded, but hopefully helpful.

**Comment by slochower** [comment] 2018-06-18 02:04
@swails thank you, this was really helpful and I appreciate the detail. I'll briefly explain what I'm trying to do and how it's related. 

I'm trying to compare parameters between `prmtop` files created with different force fields using ParmEd as an intermediary, especially with the [Open Force Field Initiative](http://openforcefield.org). I think the most comprehensive way to do this is by looping through the *atoms* in each `Structure` -- and then querying the bonds, angles, and torsions connected to each atom -- instead of looping through the parameters themselves directly. This is because when [smirnoff99Frosst](https://github.com/openforcefield/smirnoff99Frosst) parameters are written to a `prmtop`, all atoms are given a unique type, and thus there are *many* parameters in the smirnoff99Frosst `prmtop` that may not be in, for example, a GAFF `prmtop`. The bookkeeping is the main challenge. Essentially, I create a `pandas.DataFrame` for all parameters of a given type (e.g., bonds) in each structure, then try to join the `DataFrame`s on both atom indices and do some filtering to remove duplicates. 

All this is to say that I think I *do* want to stick with `AmberParm` here, because that is simply a representation of the `prmtop` file. Does that sound right to you?

Also, your explanation about the impropers makes a lot of sense!

**Comment by stefdoerr** [comment] 2018-06-22 10:04
Just FYI, this re-sorting of impropers breaks the ACEMD prmtop parser which ends up giving NaN energies. Mentioning it here since it might cause problems with other software as well.

**Comment by swails** [comment] 2018-06-22 10:39
But I didn’t change the prmtop parser?

What exactly is ACEMD doing? Because if I know, I can incorporate some automated testing to make sure things don’t break.

**Comment by stefdoerr** [comment] 2018-06-22 11:15
Hm ok so it might not be the recent changes but rather the prmtop writer itself. Because I am comparing a tleap built `prmtop` with a parmed written `prmtop` and the parmed one gives NaN energies in ACEMD. It works on my FFEvaluate class though. I'll look at the ACEMD code and see what goes wrong.

**Comment by swails** [comment] 2018-06-22 12:51
ParmEd doesn't create topology files, though.

If you're getting NaN, I'd look at the SCEE/SCNB sections, which can have 0s in them.  The values that are 0s correspond to torsion types of torsion terms whose 1-4 interactions _should_ be excluded from calculation.  But div-by-0 is a classic cause of NaNs.

**Comment by stefdoerr** [comment] 2018-06-22 13:51
For me we can close this issue unless you want to be compatible with tleap and write the scaling factors in the same order.

**Comment by swails** [comment] 2018-07-21 17:04
I'm going to go ahead and close this.

The intended behavior here is for *all but 1* of the multi-term dihedrals to get SCEE/SCNB values of 0.  Which one gets 0 and which one gets the "real" values doesn't matter, so ParmEd just picks one when it has to build a prmtop file (e.g., when converting to Amber from another format).  But it seems to me that the current behavior is more correct than the old behavior.

**Closed by swails** 2018-07-21 17:04 UTC

**Comment by stefdoerr** [comment] 2018-10-03 11:20
I'll have to necro this thread unfortunatelly. Reading some CGENFF parameters with parmed 3.0.1, the impropers atoms seem to not be sorted correctly.

![image](https://user-images.githubusercontent.com/7935362/46405811-baf43600-c709-11e8-91ba-00622423c1ea.png)

```
ipdb> prm.improper_types
OrderedDict([(('C261', 'C2O1', 'HGP1', 'N2S1'), <ImproperType; psi_k=72.000, psi_eq=0.000>), (('C252', 'C2O1', 'N2S1', 'O2D1'), <ImproperType; psi_k=120.000, psi_eq=0.000>)])
```
The central nitrogen is in the fourth position instead of the third.
