### ISSUE TITLE
bfactor

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#233] opened 2015-07-03 03:22 UTC
since b-factor is commonly used, what do you think about pdb.bfactors.

if you think it's ok, I can PR (just let me know which class is the best to put this info) or add it yourself.

```python
@property
def bfactors(self):
    return np.array([atom.bfactor for atom in self.atoms])
```

Motivation:
```python
import pytraj as pt
plot(pdb['@CA'].bfactors, pt.calc_bfactors(traj, '@CA')
```

**Comment by swails** [comment] 2015-07-03 12:36
There is no denying that wrapping up atomic properties in `Structure` arrays can be convenient when you want a simple array of all B factors (for instance).  You could say the same thing about anisotropic B-factors (the `ANISOU` records), charges, masses, etc.  But there are so many properties that we *can't* turn them all into descriptors on `Structure` for universal convenience.  Here's a short list of some of the attributes that `Atom` has that people may want access to:

- atomic_number
- name
- type
- charge
- mass
- GB radii
- GB screen
- occupancy
- bfactor
- rmin
- epsilon
- anisotropic B-factors
- multipole moments (for force fields like AMOEBA)

This is why I added `to_dataframe`, and this is the type of thing that `to_dataframe` was designed to do:

```Python
df = pdb.to_dataframe()
plot((df.name == 'CA').bfactor, pt.calc_bfactors(traj, '@CA'))
```

**Comment by hainm** [comment] 2015-07-03 19:11
Hi, you are right. Thanks. 

May be I just wrap some of attributes I am interested for pytraj (monkey patch?).

Hai

**Comment by swails** [comment] 2015-07-03 22:56
Just using a function (`get_parmed_bfactors`) might be clearer, but whatever you think is easiest to use (and hopefully maintain and understand for others) works.

FWIW, the DataFrame method is *much* faster than slicing a `Structure` with a mask and extracting B-factors.

Closing this, since this is handled with pandas.

**Closed by swails** 2015-07-03 22:56 UTC
