### ISSUE TITLE
Gromacs to Amber Conversion 

### ISSUE THREAD

**Issue by aldukhi2** [ParmEd/ParmEd#893] opened 2017-09-05 22:43 UTC
Hello all,

I've been trying for a long time to convert the topology file from GROMACS (.top) to Amber (.prmtop). The force field I'm using is gromos54a7_atb. I got the force fields and pdb files for my system from the atb website (https://atb.uq.edu.au). I used several different ways for the conversion, but every time I'd get this warning "GromacsWarning: angles funct != 1 or 5; unknown functional." When I checked the angle funct, it was 2.

From previous posts #647 and #473, it seems that such conversion is impossible as Amber does not have a corresponding feature. But since it's been around year and a half for the previous post and since a new version of ParmEd was released, I thought there could be a new development for this conversion. Could you please guide me?

**Comment by ctk3b** [comment] 2017-09-05 23:26
To the best of my knowledge, the problem is still that Amber does not support the GROMOS angle functional form (check the gromacs manual for the G96 angle - funct = 2 - for more info). If Amber does not support it, there's nothing that ParmEd can do to convert it into that format ¯\\\_(ツ)\_/¯

**Comment by swails** [comment] 2017-09-06 15:05
@ctk3b has it exactly right.  I'll only add that there is little-to-no incentive for Amber to add support for additional functional forms for valence terms, since Amber force fields have continued to improve without needing those terms (and are among the best in the field for biomolecular simulation).

I'm going to go ahead and close this, since the error here is that it's not possible even in principle (not just that ParmEd can't do it).

**Closed by swails** 2017-09-06 15:05 UTC
