### ISSUE TITLE
Conversion error for SPC/E water box from GROMACS->Amber

### ISSUE THREAD

**Issue by mrshirts** [ParmEd/ParmEd#459] opened 2015-10-19 23:29 UTC
I'm running ParmEd on a GROMACS SPC/E box (for unit tests in InterMol).  When run in sander, the converted files give a segmentation fault; it's not clear where it's occurring exactly (the mdout says, but it's not clear to me what the issue might be).

I'm sending files to Jason as an email since I do not have write permission for the repository to attach the files here.

Sending:
1. sander mdout
2. gromacs .top
3. gromacs .gro
4. amber .prmtop
5. amber .rst7

**Comment by swails** [comment] 2015-10-19 23:34
Can you post the files on Dropbox and add a link here?

**Comment by swails** [comment] 2015-10-19 23:35
Or you could file a PR with those files (which I could turn into a test case when I have it figured out what the problem is).

**Comment by mrshirts** [comment] 2015-10-19 23:35
Here's the specific code snippet used.

        if (os.path.isfile(gro_out) and os.path.isfile(top_out)):
            # if so, use these files.  Load them into ParmEd
            try:
                top = parmed.load_file(top_out, xyz=gro_out)
            except Exception as e:
                output_status['amber'] = e
            if top:
                try:
                    parm = parmed.amber.AmberParm.from_structure(top)
                    prmtop_out = oname + '.prmtop'
                    crd_out = oname + '.rst7'
                    try:
                        parm.write_parm(prmtop_out)
                    except Exception as e:
                        output_status['amber'] = e
                    try:
                        parm.write_rst7(crd_out)
                    except Exception as e:
                          output_status['amber'] = e
                if e == None:
                        output_status['amber'] = 'Converted'
          except Exception as e:
               output_status['amber'] = e

**Comment by swails** [comment] 2015-10-19 23:35
I just got the attachments, so ignore the above posts :)

**Comment by mrshirts** [comment] 2015-10-19 23:36
Sounds good!

Does correctly convert back and forth from the other programs with InterMol, but perhaps there's something wrong I'm doing in the setup.

**Comment by mrshirts** [comment] 2015-10-19 23:44
Wait, I think I've figured out I'm running from another file than I thought, which gromacs processes OK, but has some weird formatting -- hold off for a bit on debugging.

**Comment by swails** [comment] 2015-10-19 23:45
Well you can significantly simplify that code with some convenience methods in ParmEd:

```Python
        if (os.path.isfile(gro_out) and os.path.isfile(top_out)):
            # if so, use these files.  Load them into ParmEd
            try:
                top = parmed.load_file(top_out, xyz=gro_out)
            except Exception as e:
                output_status['amber'] = e
            else:
                try:
                    top.save(oname + '.prmtop')
                    top.save(oname + '.rst7')
                except Exception as e:
                    output_status['amber'] = e
                else:
                    output_status['amber'] = 'Converted'
```

Your code would have thrown a couple NameErrors, I think.  The `if top` would have (or maybe an `UnboundLocalError`) if `parmed.load_file` had failed, since it wouldn't have been assigned.  Also, `if e == None` would have failed had none of the `except` lines triggered and assigned `e` to one of the exceptions (unless, of course, `e` was assigned in the preceding code).  The above code is untested, but it should work.

It would actually be interesting to know if `Structure.save` worked, since it's a slightly different code path (and does some checks under the hood that I don't think were present in your original code).

**Comment by swails** [comment] 2015-10-19 23:46
> hold off for a bit on debugging.

Gladly :)

**Comment by mrshirts** [comment] 2015-10-19 23:47
OK, I'll try those functions.  I did actually snip out some errror handling in the code that I posed.

Also, looks like a nonstandard exclusions setup that gromacs and lammps were parsing correctly (though unexpectedly), but sander failed.  Will get back on this later tonight.

**Comment by swails** [comment] 2015-10-19 23:48
One other tip -- ParmEd has a prmtop checker that will check for issues.  Feed the prmtop into `parmed` and use the `checkValidity` command:

```
$ parmed -p <prmtop> -c <inpcrd> << EOF
checkValidity
EOF
```

**Comment by mrshirts** [comment] 2015-10-20 03:07
Thanks for the tips! They helped solve another problem (I was converting to a parm, then using write_rst7, which erased the box (though only in some cases. . . )). 

However, the files I sent you do run correctly in gromacs, and fail when converted. Basically, the exclusions are 

[ exclusions ]
      1       2
      1       3
      2       3

Which states that the interactions between all atoms on the same molecule are excluded.

The 'canonical' version of the SPCE topology has:

[ exclusions ]
1       2       3
2       1       3
3       1       2

Which also states all atoms on the same molecule are excluded

Both run the same in gromacs, but the first one gets converted into a .prmtop that crashes sander.

Let me know if you see anything I'm missing!

**Comment by swails** [comment] 2015-10-20 17:16
This is how I read the first exclusions line:

1. Atom 2 is excluded from atom 1
2. Atom 3 is excluded from atom 1
3. Atom 3 is excluded from atom 2

ParmEd always treats exclusions symmetrically.  That is, excluding atom 2 from atom 1 also excludes atom 1 from atom 2.

The second exclusion list I read as:

1. Atoms 2 and 3 are excluded from atom 1
2. Atoms 1 and 3 are excluded from atom 2
3. Atoms 1 and 2 are excluded from atom 3

I don't *think* ParmEd should be handling either of the cases differently than the other (end result is that everybody is excluded from everybody else in SPCE).  That is what [this](https://github.com/ParmEd/ParmEd/blob/master/parmed/gromacs/gromacstop.py#L657-L658) code is doing.

**Comment by mrshirts** [comment] 2015-10-20 17:17
Could be something else in the file that is causing the crash, then.  Can you reproduce the crash?

**Comment by mrshirts** [comment] 2015-10-20 17:18
Also, the input file I used was:
----------
  recomputing energies with Cartesian restraints
  &cntrl
  imin=1, 
  maxcyc = 1,
  ntb=1,
  cut=9.0 
  /

**Comment by swails** [comment] 2015-10-20 17:46
Yea, I saw that in the mdout file.  I'm getting some weird warnings when I use `checkValidity` with `parmed`:

```
> checkValidity
Determining validity of prmtop
28 total warnings

LongBondWarning: Atoms 46 (SOL 16 [OW]) and 48 (SOL 16 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.606 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 47 (SOL 16 [HW1]) and 48 (SOL 16 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 18.667 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 70 (SOL 24 [OW]) and 71 (SOL 24 [HW1]) are bonded 
                 (equilibrium length 1.000 A) but are 19.369 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 71 (SOL 24 [HW1]) and 72 (SOL 24 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 18.478 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 73 (SOL 25 [OW]) and 74 (SOL 25 [HW1]) are bonded 
                 (equilibrium length 1.000 A) but are 19.211 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 74 (SOL 25 [HW1]) and 75 (SOL 25 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 19.560 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 94 (SOL 32 [OW]) and 96 (SOL 32 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.185 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 95 (SOL 32 [HW1]) and 96 (SOL 32 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 18.690 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 100 (SOL 34 [OW]) and 102 (SOL 34 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.075 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 101 (SOL 34 [HW1]) and 102 (SOL 34 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 19.112 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 124 (SOL 42 [OW]) and 126 (SOL 42 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.442 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 125 (SOL 42 [HW1]) and 126 (SOL 42 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 19.873 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 169 (SOL 57 [OW]) and 171 (SOL 57 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.151 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 170 (SOL 57 [HW1]) and 171 (SOL 57 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 19.402 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 229 (SOL 77 [OW]) and 230 (SOL 77 [HW1]) are bonded 
                 (equilibrium length 1.000 A) but are 19.212 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 230 (SOL 77 [HW1]) and 231 (SOL 77 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 19.355 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 241 (SOL 81 [OW]) and 242 (SOL 81 [HW1]) are bonded 
                 (equilibrium length 1.000 A) but are 19.124 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 242 (SOL 81 [HW1]) and 243 (SOL 81 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 18.885 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 247 (SOL 83 [OW]) and 248 (SOL 83 [HW1]) are bonded 
                 (equilibrium length 1.000 A) but are 19.453 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 248 (SOL 83 [HW1]) and 249 (SOL 83 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 18.497 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 250 (SOL 84 [OW]) and 252 (SOL 84 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.259 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 251 (SOL 84 [HW1]) and 252 (SOL 84 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 19.682 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 253 (SOL 85 [OW]) and 254 (SOL 85 [HW1]) are bonded 
                 (equilibrium length 1.000 A) but are 19.314 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 254 (SOL 85 [HW1]) and 255 (SOL 85 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 18.402 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 277 (SOL 93 [OW]) and 279 (SOL 93 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.500 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 278 (SOL 93 [HW1]) and 279 (SOL 93 [HW2]) are bonded 
                 (equilibrium length 1.633 A) but are 19.430 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 295 (SOL 99 [OW]) and 296 (SOL 99 [HW1]) are bonded 
                 (equilibrium length 1.000 A) but are 19.543 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

LongBondWarning: Atoms 295 (SOL 99 [OW]) and 297 (SOL 99 [HW2]) are bonded 
                 (equilibrium length 1.000 A) but are 19.414 A apart. This often 
                 indicates gaps in the original sequence and should be checked 
                 carefully. 

```

This is highly unusual...  When I tried to visualize the inpcrd file in VMD, I stumbled upon the realization that VMD broke their restart file parser :(.  Not sure how/when, but it's broken and won't display any of the coordinates.  So I decided to turn the restart into a NetCDF trajectory instead (since that parser in VMD is not broken).  This is what the trajectory looked like:

![coords](https://cloud.githubusercontent.com/assets/779022/10615916/7de2d1c6-7730-11e5-94bb-222a0864849b.jpg)

That's seriously messed up.  I'm not a GROMACS expert, but I think there's a "pbc whole" option that makes sure that molecules are never "split" across different periodic images.  This is something Amber absolutely requires.  It could be that what's happening is that the exclusion list contains atoms that the pairlist *doesn't*.  This is weird, to say the least, but could certainly explain an illegal memory violation.

Where did you get this coordinate file, anyway?  And am I visualizing it wrong, somehow?

**Comment by mrshirts** [comment] 2015-10-20 17:50
Hmm, it runs perfectly fine in GROMACS and LAMMPS; perhaps they are doing the PDC automatically?  I'll look into this some more.

**Comment by swails** [comment] 2015-10-20 17:51
Do both GROMACS and LAMMPS support bonds that cross periodic boundaries?  I believe GROMACS does, but AMBER (and OpenMM) most certainly does not...

**Comment by swails** [comment] 2015-10-20 17:54
But moreover -- what's with that gap?  Even presuming you use the "-pbc whole" option to bring all atoms within a molecule to the same periodic image, where did the gap between the two water "slabs" come from?

That gap shouldn't make a big difference in terms of *running* AMBER, but unless it's expected it makes me worry a little bit about the coordinate conversion.

**Comment by davidlmobley** [comment] 2015-10-20 17:58
FWIW, these files are the result of an AMBER -> GROMACS -> AMBER conversion
(unless Michael has added another step along the way I'm not aware of) - so
as far as I'm aware nothing should be wrapped across periodic boundaries
since there has been no simulation yet (i.e., everything starts off whole
typically). So yes, I worry about the coordinate conversion too. We've
certainly validated AMBER -> GROMACS a lot but paid less attention to
GROMACS -> AMBER so maybe something is going wrong there.

Thanks.


On Tue, Oct 20, 2015 at 10:54 AM, Jason Swails <notifications@github.com>
wrote:

> But moreover -- what's with that gap? Even presuming you use the "-pbc
> whole" option to bring all atoms within a molecule to the same periodic
> image, where did the gap between the two water "slabs" come from?
>
> That gap shouldn't make a big difference in terms of *running* AMBER, but
> unless it's expected it makes me worry a little bit about the coordinate
> conversion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/459#issuecomment-149646963>.
>



-- 
David Mobley
Associate Professor
Department of Pharmaceutical Sciences
Department of Chemistry
3134B Natural Sciences I
University of California, Irvine
Irvine, CA 92697
dmobley@uci.edu
work (949) 824-6383
cell (949) 385-2436

**Comment by mrshirts** [comment] 2015-10-20 17:58
> Do both GROMACS and LAMMPS support bonds that cross periodic boundaries? 

Yes.

I can probably swap around the configuration for now, though -- this is for testing.  You don't necessarily need to require that all of the files that run in GROMACS can necessarily be coverted.  This was not genrated as part of AMBER->Gromacs->AMBER, but that's what we need working immeidately. 

I'll ho can add on the automated checking of the parmed file as part of the command line conversion program.

**Comment by mrshirts** [comment] 2015-10-20 18:10
> But moreover -- what's with that gap? Even presuming you use the "-pbc whole" option to bring all atoms within a molecule to the same periodic image, where did the gap between the two water "slabs" come from?

Long story.  Gap came from needing to make the cutoffs larger over the entire data set.  It didn't affect the existing calculations, so we didn't worry that it was a nonphysical configuration, because it was an allowed configuration.

**Comment by mrshirts** [comment] 2015-10-20 18:20
One clarification.  In the .gro file, the coordinates appear to always be within 1-1.5 A from each other (just spot checking).  It's just that some are negative numbers, and some have positive, so that if you wrap them around, then you would get separated atoms.  So that's why GROMACS thinks it's cool, I believe -- it's not wrapping them before calculating energies.  If you wrap then measure, then you would get weird results.

This seems like it should be a valid configuration -- a cubic droplet of water floating in a larger cube.  Not a practical configuration, of course (would immediately fly apart), but physical.

**Comment by mrshirts** [comment] 2015-10-20 19:55
OK, I did find some long bonds (though gromacs is still fine with the initial configuration, interestingly -- though I suspect that it would have some problems if I ran dynamics) if it's at 50 A.  

So let's go to a more reasonable initial state. If I shrink it to 20 A (the original size the box vector was (long story not worth getting into)) then we get situations like:

   16SOL     OW   46      0.781585711962      0.963840111519     -0.592484792499
   16SOL    HW1   47      0.771666459477      0.869894067858     -0.559686174988
   16SOL    HW2   48      0.862369978409     -0.994614322097     -0.550677278720

So here,  the OW and HW2 are the correct distance apart with 2.0 nm PBC. So, whether this is a valid configuration or not depends on program -- in GROMACS, PBC's are applied, and it's happy as is. In AMBER, PBC's are not applied on start, and it's not happy.

**Comment by mrshirts** [comment] 2015-10-20 19:58
Also, Desmond and LAMMPS are happy with the coordinates as is. 

So it's clear what the issue is now (lets just focus on the 20 A case); it's perhaps just not clear what the best resolution is.  One would be for InterMol to 'pbc whole' the entire system, or just make sure that all bonds are on the same size of the periodic system; another would be for ParmEd to do it.

**Comment by swails** [comment] 2015-10-21 01:02
This system would've been impossible for ParmEd to handle, because the unit cell dimensions didn't actually correspond to the ones for which the solvent was "split" across.

I could add a "pbc whole" implementation in ParmEd to my todo list.  I think I know how to do this, too.  You can use `networkx` to build the bond graph and extract groups of atoms in the molecules pretty easily.  Then just walk the bond graph recursively starting at the first atom, pulling each bonded partner to the nearest displacement.  Something like the following pseudo-code:

```Python
def pull_partners_closer(atom, visited_atoms):
    for batom in atom.bond_partners:
        if batom in visited_atoms: continue
        batom.xyz = atom.xyz + min_image_displacement(batom, atom)
        pull_partners_closer(batom, visited_atoms)

bond_graph = nx.Graph() # Build from atoms and bonds
molecules = bond_graph.get_connected_sets() # Not sure what the name of this is
for molecule in molecules:
    visited_atoms = set()
    pull_partners_closer(molecule.atoms[0], visited_atoms)
```

This will probably be slow, but I can possibly pull in numba to help here if performance simply becomes unbearably bad.

**Comment by mrshirts** [comment] 2015-10-21 01:27
> This system would've been impossible for ParmEd to handle, because the unit cell dimensions didn't actually correspond to the ones for which the solvent was "split" across.

Clarifying: I'm not talking about the 50 A box, I'm talking about when the box is reduced to 20 A.  Still fails in AMBER, runs fine in everything else (Desmond, LAMMPS, GROMACS -- Desmond fails with the 50 A box).

**Comment by mrshirts** [comment] 2015-10-21 01:28
Same coordinates, box reduced to the original 20 A.

**Comment by swails** [comment] 2015-10-21 01:34
> Same coordinates, box reduced to the original 20 A.

Right, but Amber does not do imaging for the bonded routines.

**Comment by mrshirts** [comment] 2015-10-21 01:46
Right, I'm just mentioning that as a difference that other programs handle.  If you do the imaging first with a 20 A box, then the water molecules all look normal.

**Comment by mrshirts** [comment] 2015-10-21 02:22
Note that the solution may just be catching the issue and printing a warning, or even just documenting it, rather than necessarily implementing code to adjust things for amber

**Comment by mrshirts** [comment] 2015-10-21 21:41
Quick follow up on this to get at least this example working.  

If this:

    16SOL OW 46 0.781585711962 0.963840111519 -0.592484792499
    16SOL HW1 47 0.771666459477 0.869894067858 -0.559686174988
    16SOL HW2 48 0.862369978409 -0.994614322097 -0.550677278720

Were changed to this:

    16SOL OW 46 0.781585711962 0.963840111519 -0.592484792499
    16SOL HW1 47 0.771666459477 0.869894067858 -0.559686174988
    16SOL HW2 48 0.862369978409 1.005385677903 -0.550677278720

Would it work in AMBER, then? (only change in y coordinate of HW2, + 2.0 nm)

**Comment by swails** [comment] 2015-10-21 21:42
I'm not sure -- the problem *could* be that Amber doesn't deal well with a mostly empty box.  I'll try and find some time tomorrow to really look at this closer.

**Comment by mrshirts** [comment] 2015-10-21 21:50
Again, let me emphasize as I have before in the thread -- this is for the 20 A box (not expanded to 50 A when we were fiddling around with cutoffs in testing).

**Comment by swails** [comment] 2015-10-21 22:54
Ok. Noted. I'll try this out hopefully tomorrow and report back. If it IS an Amber problem, I'd love to get it fixed.

**Comment by swails** [comment] 2015-12-21 17:13
What's the status on this?  Are there still problems here running in Amber?  I seem to have dropped the ball here...

**Comment by swails** [comment] 2017-04-15 01:48
Is this still an issue?  A *lot* has changed in the last 1.5 years or so for these kinds of conversions.

**Comment by swails** [comment] 2017-04-15 01:48
I'm going to close this -- feel free to reopen (or open a new issue) if it turns out this hasn't been fixed yet.

**Closed by swails** 2017-04-15 01:48 UTC
