### ISSUE TITLE
penalty score

### ISSUE THREAD

**Issue by ChayaSt** [ParmEd/ParmEd#133] opened 2015-05-04 20:35 UTC
When cgenff generates a stream file for a new molecule, all new parameters receive a penalty score of how good the analogy is. This penalty score is then used to decide if optimization is needed. Here is what it looks like: 

```
BONDS
CG251O CG2D2   570.00     1.3400 ! pyrrol , from CG251O CG2DC3, penalty= 210
CG251O CG3C52  300.00     1.5300 ! pyrrol , from CG2R53 CG3C52, penalty= 64
CG251O NG3C51  380.00     1.4000 ! pyrrol , from CG2R53 NG3C51, penalty= 64
CG321  NG3C51  263.00     1.4740 ! pyrrol , from CG321 NG311, penalty= 20

ANGLES
CG2D2  CG251O CG3C52   40.00    130.00 ! pyrrol , from CG2DC3 CG251O NG2R53, penalty= 268
CG2D2  CG251O NG3C51   40.00    130.00 ! pyrrol , from CG2DC3 CG251O NG2R53, penalty= 264.5
CG3C52 CG251O NG3C51  120.00    105.50 ! pyrrol , from CG3C52 CG2R53 NG2R53, penalty= 328
CG251O CG2D2  HGA5     45.00    120.50 ! pyrrol , from CG2D1 CG2D2 HGA5, penalty= 23
CG321  CG321  NG3C51   43.70    112.20 ! pyrrol , from CG331 CG321 NG311, penalty= 3.9
NG3C51 CG321  HGA2     32.40    109.50   50.00   2.13000 ! pyrrol , from NG311 CG321 HGA2, penalty= 3


DIHEDRALS
CG3C52 CG251O CG2D2  HGA5       5.2000  2   180.00 ! pyrrol , from CG321 CG2D1 CG2D2 HGA5, penalty= 295
NG3C51 CG251O CG2D2  HGA5       4.6000  2   180.00 ! pyrrol , from NG2R53 CG251O CG2DC3 HGA5, penalty= 294
CG2D2  CG251O CG3C52 CG2R51     2.0500  3   180.00 ! pyrrol , from CG2R51 CG2R51 CG3C52 CG2R51, penalty= 136.5
CG2D2  CG251O CG3C52 HGA2       0.0000  3     0.00 ! pyrrol , from CG2R51 CG2R51 CG3C52 HGA2, penalty= 136.5
NG3C51 CG251O CG3C52 CG2R51     2.0500  3   180.00 ! pyrrol , from CG2R51 CG2R51 CG3C52 CG2R51, penalty= 165.5
NG3C51 CG251O CG3C52 HGA2       0.0000  3   180.00 ! pyrrol , from NG2R53 CG2R53 CG3C52 HGA2, penalty= 148
CG2D2  CG251O NG3C51 CG2R51     8.0000  2   180.00 ! pyrrol , from CG2R51 CG2R51 NG3C51 CG3C52, penalty= 210.5
CG2D2  CG251O NG3C51 CG321      8.0000  2   180.00 ! pyrrol , from CG2R51 CG2R51 NG3C51 CG3C52, penalty= 167.5
CG3C52 CG251O NG3C51 CG2R51     4.0000  2   180.00 ! pyrrol , from NG2R50 CG2R53 NG3C51 CG3C52, penalty= 232.5
CG3C52 CG251O NG3C51 CG321      4.0000  2   180.00 ! pyrrol , from NG2R50 CG2R53 NG3C51 CG3C52, penalty= 189.5

```

It would be nice if ParmEd could read these scores.

**Comment by swails** [comment] 2015-05-05 00:25
@ChayaSt -- I issued a PR in #135 that tentatively implements this feature.  However, I've never used CGenFF, so please try out this PR and see if it fixes your issue.

To check out the PR, do this in your ParmEd repo (or the equivalent if you already know how to do this with git):

```
git remote add swails https://github.com/swails/ParmEd
git fetch swails
git checkout -b penalty swails/penalty
```

What this PR does is add a `penalty` attribute to every parameter type.  If no penalty is assigned in the comments, this penalty is simply set to `None`.  In cases where this penalty *is* known, it is set to the value from the comment of the same line of the file... at least that is the intended behavior.

As I don't have any examples, it would be great if you could test and validate this, as well as provide me with an example so I can add a test case before merging #135.

**Comment by ChayaSt** [comment] 2015-05-05 00:34
Great! will test this tomorrow and submit a PR.
Here's a link to an example stream file from CGenFF for reference:

https://raw.githubusercontent.com/choderalab/Torsions/master/structures/Pyrrol/pyrrol.str

**Comment by swails** [comment] 2015-05-05 00:49
Oh.  This PR only extracts the penalties for the parameter types, not for any of the residues (in particular the charge assignments).

Extracting penalty scores on parameter types was minimally intrusive (i.e., it was trivial to add another attribute to the base `_ParameterType` class called `penalty` and populate that as necessary).  There is not a clear-cut place to store atomic charge penalties on residue templates, so I won't get to that for awhile.

**Comment by ChayaSt** [comment] 2015-05-05 00:53
Atomic charge penalties are not that important for now since I'll only be
working with the dihedrals.

**Comment by swails** [comment] 2015-05-05 00:53
Which makes me happy :).

**Comment by swails** [comment] 2015-05-05 12:33
OK, it's not working yet.  I'm investigating.

**Comment by swails** [comment] 2015-05-05 12:52
OK, fixed, and test case added.  It seems to be working for me, so I'll merge #135 as soon as Travis finishes successfully.

**Comment by ChayaSt** [comment] 2015-05-05 14:54
It's working for me too! Thanks!

**Comment by swails** [comment] 2015-05-05 14:55
OK, then I'll close this for now.

**Closed by swails** 2015-05-05 14:55 UTC
Labels: enhancement
