### ISSUE TITLE
does not recognize alternative atoms in phenix atom order

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#772] opened 2016-11-01 19:36 UTC
Hi, 

Please see the output below
```python
import parmed as pmd

fn = 'test.pdb'
parm = pmd.load_file(fn)
print(parm.atoms)
```

normal order (ABABAB...)

```bash
ATOM     58  N   VAL     5       4.582  11.380  12.053  1.00 13.28           N
ATOM     59  H   VAL     5       3.844  10.863  12.531  1.00 13.28           H
ATOM     60  CA  VAL     5       4.579  12.794  12.393  1.00 13.13           C
ATOM     61  HA  VAL     5       5.370  13.216  11.772  1.00 13.13           H
ATOM     62  CB AVAL     5       3.411  13.602  11.939  0.55 16.58           C
ATOM     63  CB BVAL     5       3.101  13.314  12.199  0.45 17.16           C
ATOM     64  HB AVAL     5       3.629  14.615  12.277  0.55 17.16           H
ATOM     65  HB BVAL     5       2.429  12.830  12.908  0.45 17.16           H
ATOM     66  CG1AVAL     5       3.287  13.662  10.423  0.55 16.27           C
ATOM     67  CG1BVAL     5       3.035  14.797  12.450  0.45 21.90           C
ATOM     68 HG11AVAL     5       2.419  14.263  10.152  0.55 21.90           H
ATOM     69 HG11BVAL     5       2.011  15.144  12.313  0.45 21.90           H
ATOM     70 HG12AVAL     5       4.186  14.112  10.002  0.55 21.90           H
ATOM     71 HG12BVAL     5       3.356  15.008  13.470  0.45 21.90           H
ATOM     72 HG13AVAL     5       3.167  12.653  10.028  0.55 21.90           H
ATOM     73 HG13BVAL     5       3.690  15.314  11.749  0.45 21.90           H
ATOM     74  CG2AVAL     5       2.113  13.231  12.603  0.55 21.87           C
ATOM     75  CG2BVAL     5       2.672  12.986  10.766  0.45 18.29           C
ATOM     76 HG21AVAL     5       1.314  13.864  12.218  0.55 18.29           H
ATOM     77 HG21BVAL     5       1.652  13.335  10.603  0.45 18.29           H
ATOM     78 HG22AVAL     5       1.882  12.187  12.392  0.55 18.29           H
ATOM     79 HG22BVAL     5       3.342  13.482  10.063  0.45 18.29           H
ATOM     80 HG23AVAL     5       2.202  13.373  13.680  0.55 18.29           H
ATOM     81 HG23BVAL     5       2.716  11.908  10.611  0.45 18.29           H
ATOM     82  C   VAL     5       4.951  13.013  13.840  1.00 12.51           C
ATOM     83  O   VAL     5       4.663  12.216  14.725  1.00 18.54           O
```

output
```bash
AtomList([
	<Atom N [0]; In VAL 0>
	<Atom H [1]; In VAL 0>
	<Atom CA [2]; In VAL 0>
	<Atom HA [3]; In VAL 0>
	<Atom CB [4]; In VAL 0>
	<Atom HB [5]; In VAL 0>
	<Atom CG1 [6]; In VAL 0>
	<Atom HG11 [7]; In VAL 0>
	<Atom HG12 [8]; In VAL 0>
	<Atom HG13 [9]; In VAL 0>
	<Atom CG2 [10]; In VAL 0>
	<Atom HG21 [11]; In VAL 0>
	<Atom HG22 [12]; In VAL 0>
	<Atom HG23 [13]; In VAL 0>
	<Atom C [14]; In VAL 0>
	<Atom O [15]; In VAL 0>
])
```

**Comment by hainm** [comment] 2016-11-01 19:37
phenix's atom order (AAAAA...BBBBB)

```bash
ATOM     58  N   VAL     5       4.582  11.380  12.053  1.00 13.28           N
ATOM     59  CA  VAL     5       4.579  12.794  12.393  1.00 13.13           C
ATOM     60  C   VAL     5       4.951  13.013  13.840  1.00 12.51           C
ATOM     61  O   VAL     5       4.663  12.216  14.725  1.00 18.54           O
ATOM     62  H   VAL     5       3.844  10.863  12.531  1.00 13.28           H
ATOM     63  HA  VAL     5       5.370  13.216  11.772  1.00 13.13           H
ATOM     64  CB AVAL     5       3.411  13.602  11.939  0.55 16.58           C
ATOM     65  CG1AVAL     5       3.287  13.662  10.423  0.55 16.27           C
ATOM     66  CG2AVAL     5       2.113  13.231  12.603  0.55 21.87           C
ATOM     67  HB AVAL     5       3.629  14.615  12.277  0.55 17.16           H
ATOM     68 HG11AVAL     5       2.419  14.263  10.152  0.55 21.90           H
ATOM     69 HG12AVAL     5       4.186  14.112  10.002  0.55 21.90           H
ATOM     70 HG13AVAL     5       3.167  12.653  10.028  0.55 21.90           H
ATOM     71 HG21AVAL     5       1.314  13.864  12.218  0.55 18.29           H
ATOM     72 HG22AVAL     5       1.882  12.187  12.392  0.55 18.29           H
ATOM     73 HG23AVAL     5       2.202  13.373  13.680  0.55 18.29           H
ATOM     74  CB BVAL     5       3.101  13.314  12.199  0.45 17.16           C
ATOM     75  CG1BVAL     5       3.035  14.797  12.450  0.45 21.90           C
ATOM     76  CG2BVAL     5       2.672  12.986  10.766  0.45 18.29           C
ATOM     77  HB BVAL     5       2.429  12.830  12.908  0.45 17.16           H
ATOM     78 HG11BVAL     5       2.011  15.144  12.313  0.45 21.90           H
ATOM     79 HG12BVAL     5       3.356  15.008  13.470  0.45 21.90           H
ATOM     80 HG13BVAL     5       3.690  15.314  11.749  0.45 21.90           H
ATOM     81 HG21BVAL     5       1.652  13.335  10.603  0.45 18.29           H
ATOM     82 HG22BVAL     5       3.342  13.482  10.063  0.45 18.29           H
ATOM     83 HG23BVAL     5       2.716  11.908  10.611  0.45 18.29           H
```

output (having duplicated atom names)

```bash
AtomList([
	<Atom N [0]; In VAL 0>
	<Atom CA [1]; In VAL 0>
	<Atom C [2]; In VAL 0>
	<Atom O [3]; In VAL 0>
	<Atom H [4]; In VAL 0>
	<Atom HA [5]; In VAL 0>
	<Atom CB [6]; In VAL 0>
	<Atom CG1 [7]; In VAL 0>
	<Atom CG2 [8]; In VAL 0>
	<Atom HB [9]; In VAL 0>
	<Atom HG11 [10]; In VAL 0>
	<Atom HG12 [11]; In VAL 0>
	<Atom HG13 [12]; In VAL 0>
	<Atom HG21 [13]; In VAL 0>
	<Atom HG22 [14]; In VAL 0>
	<Atom HG23 [15]; In VAL 0>
	<Atom CB [16]; In VAL 0>
	<Atom CG1 [17]; In VAL 0>
	<Atom CG2 [18]; In VAL 0>
	<Atom HB [19]; In VAL 0>
	<Atom HG11 [20]; In VAL 0>
	<Atom HG12 [21]; In VAL 0>
	<Atom HG13 [22]; In VAL 0>
	<Atom HG21 [23]; In VAL 0>
	<Atom HG22 [24]; In VAL 0>
	<Atom HG23 [25]; In VAL 0>
])
```
```

**Comment by hainm** [comment] 2016-11-02 02:43
This is low priority.

**Comment by swails** [comment] 2016-11-02 10:32
I've never seen a pdb put alternate locations not immediately after the other image of the atom. 

What does the standard say?

**Comment by hainm** [comment] 2016-11-02 18:44
I just checked: http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM
and pdb does have both ways. You can search "exception that residues that have no coordinates, e.g., due to disorder, must appear in SEQRES. " in that link.

**Comment by dacase** [comment] 2019-03-21 18:12
This issue is a duplicate of #1013  Probably my fault in not seeing the earlier one.  I'll try to close this issue, since more details (and a workaround) is given in the other issue.

About the standard: if there is one, it's certainly not followed.  Some pdb entries have both of the above alternatives in the same file.

**Closed by dacase** 2019-03-21 18:12 UTC
Labels: defect
