### ISSUE TITLE
bugs/errors with iterative parmed

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#243] opened 2015-07-06 05:10 UTC
Just want to create this to report anything related to this topic.

```python
> parm
Action parm failed
        ParmError: Improper usage of `parm' command
```
after this ParmError, I was kicked out and need to `parmed mytop.parm` again.

same issue as `energy` command. (I know I did not do it right but parmed should give me a 2nd chance instead of exiting :D).

**Comment by hainm** [comment] 2015-07-06 05:13
printInfo() # for my mistake using (), I was kicked out.

```
Traceback (most recent call last):
  File "/home/haichit/anaconda3/bin/parmed", line 6, in <module>
    clapp()
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/scripts.py", line 193, in clapp
    parmed_commands.cmdloop()
  File "/home/haichit/anaconda3/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/haichit/anaconda3/lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "<string>", line 1, in <lambda>
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/parmed_cmd.py", line 150, in _normaldo
    action = ActionClass(self.parm, line)
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/actions.py", line 201, in __init__
    self.init(arg_list)
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/actions.py", line 810, in init
    SeriousParmWarning)
parmed.tools.exceptions.SeriousParmWarning: %FLAG () not found!
```

**Comment by hainm** [comment] 2015-07-06 05:16
> checkValidity
Determining validity of prmtop
DeprecationWarning: Use coordinates attribute instead of coords
LA.prmtop looks OK to me!

it is likely that 'coords' is still internally used in parmed.

**Comment by hainm** [comment] 2015-07-06 05:19
* And what is future of this interactive mode? or this will be deprecated?

**Comment by swails** [comment] 2015-07-06 12:42
> And what is future of this interactive mode? or this will be deprecated/undevloped?

It's staying, and will be further developed as well.  These are just some regressions introduced recently.

Thanks for the report.

**Comment by swails** [comment] 2015-07-06 15:18
This was an oversight of sorts.  Not a regression, but rather an assumption that was not always valid.  Basically, I equated logging actions with an interactive session (since a log file is opened and generated *only* when input is being typed at a terminal).

This assumption breaks when permissions do not allow a log file to be opened, which is what had to have happened to you.  The log file doesn't get opened so `parmed`'s error handler thought it was reading from a script.

Script vs. TTY behavior *should* be different, since the script should quit with an error at the first sign of a probable mistake.  Whereas you don't want to be kicked out of an interactive interpreter when a mistake is made (Python behaves exactly the same way with standard exceptions).

The `SeriousParmWarning` resulting in a hard error probably *was* a regression, and one that I have since fixed in #245.

**Comment by swails** [comment] 2015-07-06 15:21
FWIW, this is what I get after #245 (notice the "Could not open logfile" statement, since I'm running this in `/usr`):

```
swails@batman /usr $ parmed 

  ____    .---.  ,-----.  _____            
.'    `,.':   :'' :    :.'     `.          
| :   :    ' '     '  '   :   :  \         
|  ' '                     ' '    \        
|       v                          \       
|       |       v                   \      
|       |       |       v            \     
|   P   |   A   |   R   |   M   |     \    
|       |       |       |       |      \   
|       |       |       |       |       \  
|       |       |       |       |        \ 
| ===== |       |       |       |         )
 \ --- /| ===== |       |       |        / 
  `---'  \ --- /| ===== | ===== |       /  
          `---'  \ ---- A ----- /      /   
                  `----'.`-----'      /    
                       /             /     
                       '-._    ED   /      
                           '.      /       
                             `----' 

ParmEd: a Parameter file Editor


Could not open logfile. Skip logging
Reading input from STDIN...
> parm
Action parm failed
	ParmError: Improper usage of `parm' command
> parm /home/swails/amber/AmberTools/test/parmed/normal_prmtop/trx.prmtop
Adding prmtop /home/swails/amber/AmberTools/test/parmed/normal_prmtop/trx.prmtop to parm list. /home/swails/amber/AmberTools/test/parmed/normal_prmtop/trx.prmtop is the active parm.
> printInfo()
Action printInfo failed
	SeriousParmWarning: %FLAG () not found!
> quit
Done!
```

**Comment by hainm** [comment] 2015-07-06 15:21
thanks.

is there anyway to turn off writing log?

On Mon, Jul 6, 2015 at 11:18 AM, Jason Swails <notifications@github.com>
wrote:

> This was an oversight of sorts. Not a regression, but rather an assumption
> that was not always valid. Basically, I equated logging actions with an
> interactive session (since a log file is opened and generated *only* when
> input is being typed at a terminal).
>
> This assumption breaks when permissions do not allow a log file to be
> opened, which is what had to have happened to you. The log file doesn't get
> opened so parmed's error handler thought it was reading from a script.
>
> Script vs. TTY behavior *should* be different, since the script should
> quit with an error at the first sign of a probable mistake. Whereas you
> don't want to be kicked out of an interactive interpreter when a mistake is
> made (Python behaves exactly the same way with standard exceptions).
>
> The SeriousParmWarning resulting in a hard error probably *was* a
> regression, and one that I have since fixed in #245
> <https://github.com/ParmEd/ParmEd/pull/245>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/243#issuecomment-118888286>.
>



-- 
Hai Nguyen

**Comment by hainm** [comment] 2015-07-06 15:22
thanks. I will try when you merge to master.

On Mon, Jul 6, 2015 at 11:21 AM, Jason Swails <notifications@github.com>
wrote:

> FWIW, this is what I get after #245
> <https://github.com/ParmEd/ParmEd/pull/245> (notice the "Could not open
> logfile" statement, since I'm running this in /usr):
>
> swails@batman /usr $ parmed
>
>   ____    .---.  ,-----.  _____
> .'    `,.':   :'' :    :.'     `.
> | :   :    ' '     '  '   :   :  \
> |  ' '                     ' '    \
> |       v                          \
> |       |       v                   \
> |       |       |       v            \
> |   P   |   A   |   R   |   M   |     \
> |       |       |       |       |      \
> |       |       |       |       |       \
> |       |       |       |       |        \
> | ===== |       |       |       |         )
>  \ --- /| ===== |       |       |        /
>   `---'  \ --- /| ===== | ===== |       /
>           `---'  \ ---- A ----- /      /
>                   `----'.`-----'      /
>                        /             /
>                        '-._    ED   /
>                            '.      /
>                              `----'
>
> ParmEd: a Parameter file Editor
>
>
> Could not open logfile. Skip logging
> Reading input from STDIN...
> > parm
> Action parm failed
>     ParmError: Improper usage of `parm' command
> > parm /home/swails/amber/AmberTools/test/parmed/normal_prmtop/trx.prmtop
> Adding prmtop /home/swails/amber/AmberTools/test/parmed/normal_prmtop/trx.prmtop to parm list. /home/swails/amber/AmberTools/test/parmed/normal_prmtop/trx.prmtop is the active parm.
> > printInfo()
> Action printInfo failed
>     SeriousParmWarning: %FLAG () not found!
> > quit
> Done!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/243#issuecomment-118889237>.
>



-- 
Hai Nguyen

**Comment by swails** [comment] 2015-07-06 15:24
> is there anyway to turn off writing log?

Set the log file to `/dev/null`:

```
$ parmed -l /dev/null
```

**Comment by hainm** [comment] 2015-07-06 15:25
thx.

**Comment by swails** [comment] 2015-07-06 15:27
On the whole, the log file is a good thing, IMO.  Makes it easy to try some stuff in an interactive interpreter, then convert what you did into a script easily.  It also loads the log file into the history, so you can press the up-arrow (or CTRL-P) to scroll back through commands you ran in previous sessions.

ParmEd does basically exactly what cpptraj does (and I redirect the log file to `/dev/null` when I don't want to print it with cpptraj as well).

**Comment by hainm** [comment] 2015-07-06 15:29
good point.

On Mon, Jul 6, 2015 at 11:27 AM, Jason Swails <notifications@github.com>
wrote:

> On the whole, the log file is a good thing, IMO. Makes it easy to try some
> stuff in an interactive interpreter, then convert what you did into a
> script easily. It also loads the log file into the history, so you can
> press the up-arrow (or CTRL-P) to scroll back through commands you ran in
> previous sessions.
>
> ParmEd does basically exactly what cpptraj does (and I redirect the log
> file to /dev/null when I don't want to print it with cpptraj as well).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/243#issuecomment-118890766>.
>



-- 
Hai Nguyen

**Comment by swails** [comment] 2015-07-06 16:25
Merged.  Go ahead and give it a try.

**Closed** 2015-07-06 16:25 UTC

**Comment by hainm** [comment] 2015-07-06 16:29
thanks. work now.

On Mon, Jul 6, 2015 at 12:25 PM, Jason Swails <notifications@github.com>
wrote:

> Merged. Go ahead and give it a try.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/243#issuecomment-118916816>.
>



-- 
Hai Nguyen

**Comment by hainm** [comment] 2015-07-06 16:33
@swails is there any intention to wrap minimization for sander/pmemd (I know there is one with openmm) ?

something like
```python
new_coords = pmd.tools.minimize(parm, coords, sander_path=amberhome_bin_sander_dir)
```

**Comment by swails** [comment] 2015-07-06 18:05
Not on the immediate agenda through sander's minimizer (it sucks).  You can do this through `scipy.minimize` fairly easily, though.  I've put a code snippet that does minimization using LBFGS with scipy and the sander minimizer in several of my presentations about the sander API.

```Python
import parmed as pmd
import sander
from scipy.optimize import minimize

def target(x):
    """ Target function to minimize -- just the energy """
    sander.set_positions(x)
    e, f = sander.energy_forces()
    return e.tot, -np.array(f) # forces are -gradient

parm = pmd.load_file('something.parm7', 'something.rst7')
inp = sander.pme_input()
with sander.setup(parm, parm.coordinates, parm.box, inp):
    res = minimize(target, parm.coordinates.flatten(), method='L-BFGS-B',
                   jac=True, tol=1e-8, options=dict(maxiter=10000, disp=True))

parm.coordinates = res.x
```

**Comment by hainm** [comment] 2015-07-06 18:09
thanks.

On Mon, Jul 6, 2015 at 2:05 PM, Jason Swails <notifications@github.com>
wrote:

> Not on the immediate agenda through sander's minimizer (it sucks). You can
> do this through scipy.minimize fairly easily, though. I've put a code
> snippet that does minimization using LBFGS with scipy and the sander
> minimizer in several of my presentations about the sander API.
>
> import parmed as pmdimport sanderfrom scipy.optimize import minimize
> def target(x):
>     """ Target function to minimize -- just the energy """
>     sander.set_positions(x)
>     e, f = sander.energy_forces()
>     return e.tot, -np.array(f) # forces are -gradient
>
> parm = pmd.load_file('something.parm7', 'something.rst7')
> inp = sander.pme_input()with sander.setup(parm, parm.coordinates, parm.box, inp):
>     res = minimize(target, parm.coordinates.flatten(), method='L-BFGS-B',
>                    jac=True, tol=1e-8, options=dict(maxiter=10000, disp=True))
>
> parm.coordinates = res.x
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/243#issuecomment-118940795>.
>



-- 
Hai Nguyen

**Comment by swails** [comment] 2015-07-06 18:22
This could be a useful example, too.

**Comment by hainm** [comment] 2015-07-07 02:53
This time I was kicked out by `sander` (I know I did it wrong).

```python
> energy
Computing a single-point energy for OMGN.prmtop
DeprecationWarning: Use coordinates attribute instead of coords
DeprecationWarning: Use coordinates attribute instead of coords
Traceback (most recent call last):
  File "/home/haichit/anaconda3/bin/parmed", line 6, in <module>
    clapp()
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/scripts.py", line 194, in clapp
    parmed_commands.cmdloop()
  File "/home/haichit/anaconda3/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/haichit/anaconda3/lib/python3.4/cmd.py", line 217, in onecmd
    return func(arg)
  File "<string>", line 1, in <lambda>
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/parmed_cmd.py", line 150, in _normaldo
    action.execute()
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/actions.py", line 3430, in execute
    energy(self.parm, self.arg_list, self.output)
  File "/home/haichit/anaconda3/lib/python3.4/site-packages/parmed/tools/simulations/sanderapi.py", line 72, in energy
    sander.setup(parm, parm.coords, parm.box, inp)
  File "/home/haichit/amber_git/amber/lib/python3.4/site-packages/sander/__init__.py", line 177, in __init__
    _pys.setup(parm, coordinates, box, mm_options)
TypeError: 2nd argument must be a list
```

**Comment by hainm** [comment] 2015-07-07 02:56
if I load a pdb file and use `energy`, I got this. Two error messages are not consistent. I think they should be more descriptive. 

```python
> energy
Computing a single-point energy for <Structure 451 atoms; 14 residues; 0 bonds; PBC (orthogonal); NOT parametrized>
Action energy failed
        SimulationError: OpenMM could not be imported. Skipping.
```

**Comment by hainm** [comment] 2016-01-27 20:48
@swails 

is there any chance to have restraint for minimization with sander (in parmed context).

**Comment by swails** [comment] 2016-01-27 20:50
kind of.  With the `OpenMM` command it can read a minimization input file and do a minimization that way.  If you have restraints in your input file, it will apply those to the minimization.

**Comment by hainm** [comment] 2016-01-27 20:56
I meant with `sander`. (I guess Not, right?)

**Comment by swails** [comment] 2016-01-27 20:56
Correct, not at the moment, anyway.

**Comment by hainm** [comment] 2016-01-27 20:57
is it easy to add to pysander? If yes, I can have a look. :D

**Comment by swails** [comment] 2016-01-27 20:59
I think it *would* be easy -- you'd just have to expose the ntr, restraint_wt, and restraintmask variables through the input struct, then translate that to the CPython interface.

I'll have a go at it in the next day or two.

**Comment by hainm** [comment] 2016-01-27 21:00
> I'll have a go at it in the next day or two.

awesome. This will be great help.
