### ISSUE TITLE
numpy: does user need this to use AT?

### ISSUE THREAD

**Issue by hainm** [ParmEd/ParmEd#231] opened 2015-07-02 19:14 UTC
Jason,

numpy is optional for users to use `parmed` in AT (>= 16), right? Like if he/she just need `parmed` to inspect Topology, there is no need to have np. (although I can try myself but it's faster to ask you :D).

Hai

**Comment by davidlmobley** [comment] 2015-07-02 19:16
Numpy is now required for `parmed`.

**Comment by hainm** [comment] 2015-07-02 19:24
@davidlmobley 

I asked this because several programs in AmberTools are using `parmed`. Asking Amber users must install numpy to use AmberTools is too much.

**Comment by hainm** [comment] 2015-07-02 19:26
uhm, I just checked AT code and found that only mmpbsa_py package is using `parmed`. If users want to use `mpi4py` with this, there still need numpy anyway.

**Comment by swails** [comment] 2015-07-02 20:09
I'm not maintaining separate code bases for AmberTools and standalone ParmEd just to avoid requiring numpy.  I'm only one person, after all ;).

> Asking Amber users must install numpy to use AmberTools is too much.

I disagree with this.  Look what we *already* ask users to do on http://ambermd.org/ubuntu.html.  All we need to do is move `python-numpy` from the "suggested" to the "required" list, and we're done.  No extra work for the users.  Furthermore, not having numpy doesn't bring down AmberTools, it just prevents you from being able to use ParmEd or any ParmEd-powered program (like MMPBSA.py and pysander, for instance).

numpy isn't a troublesome dependency *nearly* as much as Python 2.7+ is (since the latter may require users to figure out how to install Py27 in some way).  But with Anaconda out there and Miniconda freely available, this is becoming far less limiting.  And it's becoming increasingly the case that peoples' favorite OSes run Py27 as their system Python (or even later versions).

> If users want to use mpi4py with this, there still need numpy anyway.

This isn't actually true.  mpi4py doesn't have a numpy dependency that I'm aware of (and people have been using it for some time without numpy...)

But even so, MMPBSA.py will start requiring numpy and Python 2.7+.

**Comment by davidlmobley** [comment] 2015-07-02 20:16
Yes, I completely agree with Jason here. Anaconda basically means that
having numpy is as simple as "go get Anaconda" and works in an essentially
platform-independent way, which is way more than you can say for many
prerequisites for a lot of code bases. I was teaching a modeling class this
year with people on a wide variety of platforms (and have also had
undergrads with a similar array) and no one has had any trouble with the
"get anaconda running on your computer" step of my instructions. They have
trouble later, but getting numpy running in anaconda Python is apparently
painless for all of them.

On Thu, Jul 2, 2015 at 1:09 PM, Jason Swails <notifications@github.com>
wrote:

> I'm not maintaining separate code bases for AmberTools and standalone
> ParmEd just to avoid requiring numpy. I'm only one person, after all ;).
>
> Asking Amber users must install numpy to use AmberTools is too much.
>
> I disagree with this. Look what we *already* ask users to do on
> http://ambermd.org/ubuntu.html. All we need to do is move python-numpy
> from the "suggested" to the "required" list, and we're done. No extra work
> for the users. Furthermore, not having numpy doesn't bring down AmberTools,
> it just prevents you from being able to use ParmEd or any ParmEd-powered
> program (like MMPBSA.py and pysander, for instance).
>
> numpy isn't a troublesome dependency *nearly* as much as Python 2.7+ is
> (since the latter may require users to figure out how to install Py27 in
> some way). But with Anaconda out there and Miniconda freely available, this
> is becoming far less limiting. And it's becoming increasingly the case that
> peoples' favorite OSes run Py27 as their system Python (or even later
> versions).
>
> If users want to use mpi4py with this, there still need numpy anyway.
>
> This isn't actually true. mpi4py doesn't have a numpy dependency that I'm
> aware of (and people have been using it for some time without numpy...)
>
> But even so, MMPBSA.py will start requiring numpy and Python 2.7+.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParmEd/ParmEd/issues/231#issuecomment-118152464>.
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by hainm** [comment] 2015-07-02 20:30
ok. I see. I totally agree with @swails  and @davidlmobley's rationale about using `numpy`. 
And `conda` is really great. 

PS: changing user's habit is really really hard. For example, in Amber mailinglist, Amber developers need to constantly remind users to use `autoimage`. :D 

Even with `Guido van Rossum` (creator of python) was originally not interested solving python packing problem until Travis Oliphant with his team made `conda`.

**Comment by hainm** [comment] 2015-07-02 20:31
> This isn't actually true. mpi4py doesn't have a numpy dependency that I'm aware of (and people have been using it for some time without numpy...)

I've just checked and yeah. `mpi4py` use `cython`.

**Comment by swails** [comment] 2015-07-02 22:01
> Even with Guido van Rossum (creator of python) was originally not interested solving python packing problem until Travis Oliphant with his team made conda.

I wouldn't say this is entirely accurate.  pip was intended to try and address this problem (and there was stuff like easy_install before that), and wheel and egg files are similarly targeted to address parts of it.

The main sticking point, and the reason why conda was created in the first place, is that pip, wheels, and eggs reside for the most part within the Python shell.  Certain pip-installable packages, like netCDF4, for instance, are C extensions that link to C libraries.  *This* is where existing Python package managers and dependency resolution schemes fall flat.  They don't know anything about non-Python stuff, so they don't even try and address the NetCDF library dependency.  If it's not already satisfied, pip simply fails.

In the scipy ecosystem more than any other in Python (that I'm familiar with), these C-library dependencies are vitally important, so pip-like tools kind of fall flat on their faces.

**Comment by hainm** [comment] 2015-07-02 22:07
ah, you're right.

And there won't be `pytraj` with pip. :(

**Comment by swails** [comment] 2015-07-02 23:04
> Do you intend to push parmed to pypi?

I had thought about it.  The only real reason I would is to call dibs on the name :)

**Comment by swails** [comment] 2015-07-03 22:57
At the end of the day, numpy is a required prereq for all ParmEd users (including those that will be using AmberTools 16 and later).  Closing this.

**Closed by swails** 2015-07-03 22:57 UTC
