### ISSUE TITLE
Summary of problems with loading all Amber FFs 

### ISSUE THREAD

**Issue by rafwiewiora** [ParmEd/ParmEd#593] opened 2016-02-05 16:00 UTC
A few groups of problems here:

1. blank lines in .lib files: all_aminoAM1.lib, all_aminoAM3.lib (called by leaprc.ffAM1 and leaprc.ffPM3), both line 1373. Causes ValueError here: https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/offlib.py#L168

2. cannot understand a line - bond or angle lines:

 all_modrna08.frcmod (leaprc.modrna08)
 ```
parmed.exceptions.ParameterError: Could not understand BOND line [C -CM 449.9   1.461   same as c -c2]
```

 parm91X.ua.dat (leaprc.ff84, leaprc.ma.ff84) and parm91X.dat (leaprc.ff86):
 ```
parmed.exceptions.ParameterError: Could not understand ANGLE line [OW-HW  553.0    0.9572]
```

3. HEAD atom is not connect0:
 ```
Traceback (most recent call last):
  File "try_one_leaprc.py", line 27, in <module>
    params = pmd.amber.AmberParameterSet.from_leaprc(leaprc)
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/amber/parameters.py", line 265, in from_leaprc
    AmberOFFLibrary.parse(_find_amber_file(fname))
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/amber/offlib.py", line 140, in parse
    residues[name] = AmberOFFLibrary._parse_residue(fileobj, name)
  File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/amber/offlib.py", line 331, in _parse_residue
    raise RuntimeError('HEAD atom is not connect0')
RuntimeError: HEAD atom is not connect0
```

 for lipid11.lib (leaprc.lipid11), lipid14.lib (leaprc.lipid14), cph_nucleic_caps.lib (leaprc.constph)

4. Access to lib/oldff, missing from `find_amber_file`: https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/parameters.py#L44 

5. phosphoaa10.lib file does not exist, replaced by individual calls to each phospho-residues in leaprc.phosaa10, but not in leaprc.ff10. Of course nothing to fix here in ParmEd, only adding for reference.

**Comment by rafwiewiora** [comment] 2016-02-05 16:00
I'm happy to look into these more / help out / whatever saves you time if you want! :)

**Comment by swails** [comment] 2016-02-05 16:21
> cannot understand a line - bond or angle lines:
> 
> all_modrna08.frcmod (leaprc.modrna08)

I think this is caused because technically there should not be spaces between type name and - (it should be " C-" rather than "C -").  It should be simple to update the parser for this.

> parm91X.ua.dat (leaprc.ff84, leaprc.ma.ff84) and parm91X.dat (leaprc.ff86):

I'm not even going to try these.  I have no idea what a 2-type angle even means!  I have guesses, but no quick and simple way to validate those guesses.  Since these occur in files that predate the Cornell FFs (by a substantial margin), these are not worth converting.  There are things you probably don't even realize about these force fields -- like the fact that the 1-4 scaling factors are *not* 1.2 elec and 2.0 vdw.  They're different (but I don't recall off the top of my head what they are).  There are no wild-card angles ever defined anymore (which is what I presume is happening here), so this is not worth spending time to fix.

> HEAD atom is not connect0:
> 
```
> Traceback (most recent call last):
> File "try_one_leaprc.py", line 27, in <module>
>   params = pmd.amber.AmberParameterSet.from_leaprc(leaprc)
> File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/amber/parameters.py", line 265, in from_leaprc
>   AmberOFFLibrary.parse(_find_amber_file(fname))
> File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/amber/offlib.py", line 140, in parse
>   residues[name] = AmberOFFLibrary._parse_residue(fileobj, name)
> File "/Users/rafalpwiewiora/anaconda/lib/python2.7/site-packages/ParmEd-2.2.0-py2.7-macosx-10.5-x86_64.egg/parmed/amber/offlib.py", line 331, in _parse_residue
>   raise RuntimeError('HEAD atom is not connect0')
> RuntimeError: HEAD atom is not connect0
```
> for lipid11.lib (leaprc.lipid11), lipid14.lib (leaprc.lipid14), cph_nucleic_caps.lib (leaprc.constph)

I can look into what's happening here.  I was overly defensive on purpose with flagging erroneous behavior in many of my parsers.  Easier to add flexibility than find (then fix) bugs.

> Access to lib/oldff, missing from find_amber_file: https://github.com/ParmEd/ParmEd/blob/master/parmed/amber/parameters.py#L44

I'd support having a way of getting `find_amber_file` to look in this directory, but not by default.  Stuff is in `lib/oldff` on purpose, and `AmberParameterSet` currently behaves the way tleap does, which is advantageous when sourcing a leaprc :smiley:

> phosphoaa10.lib file does not exist, replaced by individual calls to each phospho-residues in leaprc.phosaa10, but not in leaprc.ff10. Of course nothing to fix here in ParmEd, only adding for reference.

Good to know.

Thanks!

**Comment by rafwiewiora** [comment] 2016-02-05 16:32
> I think this is caused because technically there should not be spaces between type name and - (it should be " C-" rather than "C -"). It should be simple to update the parser for this.

That's right, I've checked this out yesterday - the regex just doesn't understand because of the space. 

> I'm not even going to try these. I have no idea what a 2-type angle even means! I have guesses, but no quick and simple way to validate those guesses. Since these occur in files that predate the Cornell FFs (by a substantial margin), these are not worth converting. There are things you probably don't even realize about these force fields -- like the fact that the 1-4 scaling factors are not 1.2 elec and 2.0 vdw. They're different (but I don't recall off the top of my head what they are). There are no wild-card angles ever defined anymore (which is what I presume is happening here), so this is not worth spending time to fix.

Alright! Yeah, I was a bit creeped out dealing with files that are older than me! :) 


> I'd support having a way of getting find_amber_file to look in this directory, but not by default. Stuff is in lib/oldff on purpose, and AmberParameterSet currently behaves the way tleap does, which is advantageous when sourcing a leaprc

So what is the rule behind lib/oldff. I'm a bit confused because of the disconnection between what's in cmd/oldff and what's in lib/oldff. For example the 99 FFs are in cmd/lib but they use files from the 'normal' lib. Is lib/oldff a graveyard for files that are not recommended not because of oldness as such but because they have corrected versions? I know that's the case with ff03 vs ff03.r1 for example.

**Comment by rafwiewiora** [comment] 2016-02-05 19:33
Just as a note, no action necessary:

* SEP.lib and S1P.lib (which are phosphorylated residues called by leaprc.phosaa10) have a wrong child sequence - 3 where 2 is expected, single residue files

**Comment by swails** [comment] 2016-02-06 22:55
OK, I have no idea how we should do the Lipid force fields.  Amber's workflow is *weird*.  Here's the general gist:

1. Use CHARMM-GUI to build a lipid bilayer system
2. Run `charmmlipid2amber.py` on it which reads from a large CSV database that basically says where to split each lipid molecule into separate residues which are the fragments defined in the lipid OFF files.
3. Run tleap on that PDB and deal with potentially *thousands* of warning messages about residues being split.

This kind of workflow does not lend itself to simple conversion like the CHARMM files do.  But the fragmentation approach that Amber took (using a workflow that piggybacks on top of CHARMM's support) doesn't seem that straightforward to me to convert.  This has led to the residue templates defining the head and tail atom as the same, so that the sequence does not matter (and RES1->RES2 will yield the same structure as RES2->RES1).  Does OpenMM even support something like that? (ping @peastman).

This isn't my problem, obviously, and I can fix the parsers so they handle these files, but you're on your own when it comes to converting both the Lipid14 and GLYCAM residue templates...

**Comment by rafwiewiora** [comment] 2016-02-07 00:19
Alright thanks a lot for looking into this!

> but you're on your own when it comes to converting both the Lipid14 and GLYCAM residue templates...

Let's see what @jchodera thinks about whether it's worth the effort.

**Comment by swails** [comment] 2016-02-08 18:37
Fixed in #594.  We can open a separate issue on the conversion of the GLYCAM/Lipid force fields.  Maybe we should set up another git repo (possibly in the choderalab organization) where we collaborate on the actual scripts that will be performing these conversions?

It would be a good place to have conversations and share code that don't really pertain to the ParmEd code base.

**Closed by swails** 2016-02-08 18:37 UTC

**Comment by rafwiewiora** [comment] 2016-02-08 21:15
> Maybe we should set up another git repo (possibly in the choderalab organization) where we collaborate on the actual scripts that will be performing these conversions?
> 
> It would be a good place to have conversations and share code that don't really pertain to the ParmEd code base.

Good idea! I will make a repo in choderalab. For the protein/nucleic conversions I will already also open a PR on the OpenMM tracker later today - because this is the time where we need Peter's approvals already for the shape of the ffxml.

**Comment by jchodera** [comment] 2016-02-08 22:10
Presumably these conversion scripts will eventually go into the `openmm` repo, so what about an `openmm` fork in `choderalab`?

**Comment by swails** [comment] 2016-02-09 02:15
I think it'll be easier to have them in their own repo (as a forum for discussion and such) and then dump them into OpenMM wholesale when they're ready(er).

Remember forks don't get their own issue trackers (you can just submit PRs to them).  I think it would also help encapsulate some of the noise a bit.  The issues in a dedicated repo would be more focused on the issues of concern to that particular work.  It wouldn't get diluted with the 100s of open issues on the OMM repo, and we wouldn't be adding noise to a repo already overflowing with open issues with threads of interest to only a small number of people.  I don't think development hurdles/issues of conversion scripts are of direct concern to the standard OMM user or developer (and we can always cross-reference issues if need be).

**Comment by jchodera** [comment] 2016-02-09 02:26
Good point, but this will create a lot more work in the end since we will need to also make sure these scripts are tested by the CI framework, meaning we'll need to hook tests into the right places.  We don't want to be in a situation like before, where `devtools/forcefield-conversion/` was full of old dead scripts that don't actually work and nobody can reproduce the forcefield conversion.

**Comment by swails** [comment] 2016-02-09 02:30
I don't see how any of that is challenging.  The hard part would be getting CI testing implemented and working anywhere we decide to start this stuff.  Once it's working in a dedicated repo, it's pretty easy to copy over the necessary components to get it working in OpenMM if we wanted to have CI testing there.

Another option, and possibly better here, is to use `git-subtree` to sync the version in the OpenMM repository with the dedicated repo we set up here.  That would keep these scripts a dedicated part of the OpenMM repo while still keeping a healthy development environment in a dedicated, streamlined repository on Github.  It would allow us to keep the CI testing simple without adding complexity to OpenMM's already very complex CI infrastructure.

**Comment by jchodera** [comment] 2016-02-09 02:39
If the presence of issues is the biggest concern, why not just turn issues on in the fork?

Settings -> Issues

**Comment by jchodera** [comment] 2016-02-09 02:40
Honestly, we really need to wrap this up this week.  So we should be putting these things into something very much resembling their final homes at this point, not an intermediate repo that will take another couple of days to reformat for openmm.

I appreciate the suggestion, but we're in endgame now.  We should be close to assembling the final PR, not setting up a separate repo.

**Comment by swails** [comment] 2016-02-09 02:52
> If the presence of issues is the biggest concern, why not just turn issues on in the fork?
> 
> Settings -> Issues

I didn't realize that was possible.

This workflow also works, as long as we're not submitting to the master branch of the choderalab fork.

> Honestly, we really need to wrap this up this week. So we should be putting these things into something very much resembling their final homes at this point, not an intermediate repo that will take another couple of days to reformat for openmm.
> 
> I appreciate the suggestion, but we're in endgame now. We should be close to assembling the final PR, not setting up a separate repo.

Works for me.  If you set it up and tag me somewhere to make me aware of where to look I'll see it.

**Comment by jchodera** [comment] 2016-02-09 02:54
Done: http://github.com/choderalab/openmm

**Comment by peastman** [comment] 2016-02-09 18:06
> Honestly, we really need to wrap this up this week.

Remember, this is a feature for 7.1.  I don't think there's any great hurry about deciding where the scripts will live.

> We don't want to be in a situation like before, where devtools/forcefield-conversion/ was full of old dead scripts that don't actually work and nobody can reproduce the forcefield conversion.

Not true at all!  All the scripts worked exactly as they were written to, and could reproduce the conversions they were used for.  You just expected them to be something different from what they were.  They were special purpose scripts written to convert specific force fields, whereas you expected them to be general purpose scripts that could handle any force field in the given format.

**Comment by jchodera** [comment] 2016-02-09 18:07
> Remember, this is a feature for 7.1. I don't think there's any great hurry about deciding where the scripts will live.

The hurry is that my folks can't spare the time to work on this beyond this week.
