### ISSUE TITLE
parmed CharmmPsfFile seems to ignore hydrogen constraints when creating a openMM system

### ISSUE THREAD

**Issue by wiederm** [ParmEd/ParmEd#1020] opened 2018-11-15 17:43 UTC
Hi!

I came across some strange behavior when creating a system using a psf file. It appears that when I use the parmed CharmmPsfFile Class to read in a psf file BondedForces for Hydrogen - Heavy Atoms are generated in the openMM system even if I specify contraints=app.Hbonds. 

An example output is:
HarmonicBondForce
Number of bonds: 7
Bond-ID:   0 Atom-ID1:   0 Atom-ID2:   4 length: 0.15375000000000003 nm k: 251793.12 kJ/(nm**2 mol)
Bond-ID:   1 Atom-ID1:   0 Atom-ID2:   1 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   2 Atom-ID1:   0 Atom-ID2:   2 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   3 Atom-ID1:   0 Atom-ID2:   3 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   4 Atom-ID1:   4 Atom-ID2:   5 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   5 Atom-ID1:   4 Atom-ID2:   6 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   6 Atom-ID1:   4 Atom-ID2:   7 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)

Using the openmm CharmmPsfFile class this is not the case (and it should not be the case). 
Example output:
HarmonicBondForce
Number of bonds: 1
Bond-ID:   0 Atom-ID1:   0 Atom-ID2:   4 length: 0.15375000000000003 nm k: 251793.12 kJ/(nm**2 mol)

I attached a zip archive with an example script to reproduce the issue.
[parmed-charmm.zip](https://github.com/ParmEd/ParmEd/files/2586437/parmed-charmm.zip)

best,
marcus

**Comment by swails** [comment] 2019-03-31 19:32
I know it's been awhile since this issue was raised, but there's no bug here.  You didn't actually look at constraints, you looked at bonds.  The existence of a bond does *not* actually imply there is no constraint.  You need to look at the constraints themselves to determine whether or not they exist.

There are valid reasons you may want to have both the valence energy terms as well as the constraints:

1 Without adding those terms you lose that information in the XML file, making it impossible to translate it into another format later (say back into a CHARMM PSF+PRM or an Amber topology file).
1. Without adding those terms you can't later *remove* some of the constraints if you want to let a particular DoF fluctuate

The added computational cost of some extra bonds is negligible (the *entire* bond calculation is minuscule compared to the nonbonded calculation).

If you add the following code to the end of your system printout:

```python
    print('There are %d constraints' % system.getNumConstraints())
    for i in range(system.getNumConstraints()):
        a_i, a_j, dist = system.getConstraintParameters(i)
        print('Constraint exists between atoms %d -- %d (%.2f nm)' % (a_i, a_j, dist.value_in_unit(unit.nanometer)))
```

You'll get the following output:

```
Using CPU for simulations ...
28954.84437484335 kJ/mol
########################################
########################################
########################################
HarmonicBondForce
Number of bonds: 7
Bond-ID:   0 Atom-ID1:   0 Atom-ID2:   4 length: 0.15375000000000003 nm k: 251793.12 kJ/(nm**2 mol)
Bond-ID:   1 Atom-ID1:   0 Atom-ID2:   1 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   2 Atom-ID1:   0 Atom-ID2:   2 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   3 Atom-ID1:   0 Atom-ID2:   3 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   4 Atom-ID1:   4 Atom-ID2:   5 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   5 Atom-ID1:   4 Atom-ID2:   6 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
Bond-ID:   6 Atom-ID1:   4 Atom-ID2:   7 length: 0.10969000000000001 nm k: 276646.08 kJ/(nm**2 mol)
There are 6 constraints
Constraint exists between atoms 0 -- 1 (0.11 nm)
Constraint exists between atoms 0 -- 2 (0.11 nm)
Constraint exists between atoms 0 -- 3 (0.11 nm)
Constraint exists between atoms 4 -- 5 (0.11 nm)
Constraint exists between atoms 4 -- 6 (0.11 nm)
Constraint exists between atoms 4 -- 7 (0.11 nm)
```

Also note that constraints are applied during the course of minimization or dynamics (in minimization, to make things easier, I believe that constraints are actually converted into *restraints* with enormous force constants so you don't need to use a minimization algorithm that works with constraints -- you can use simple L-BFGS).  What you did in your sample script was to set the positions and then immediately compute the energy.  If instead you ran dynamics or minimization (and allowed the constraints to actually be solved and applied), you would find that the bonds are returned to their constrained values.

Note that ParmEd actually provides you the option of omitting these constrained terms.  OpenMM actually provides exactly the same option (the OpenMM version is an earlier version of the ParmEd parsers that I ported over about 5 years ago).  The only difference is that the default for the OpenMM API is to omit the terms while the default for the ParmEd parsers is to include them.  The reason behind this is because ParmEd's mission is different and the more information that is retained, the more things you can do with those files within ParmEd later.

The relevant option is called `flexibleConstraints` to the `createSystem` call.  Here is the relevant documentation in the docstring:

```
        flexibleConstraints : bool=True
            If False, the energies and forces from the constrained degrees of
            freedom will NOT be computed. If True, they will (but those degrees
            of freedom will *still* be constrained).
```

So if you put `flexibleConstraints=False`, those terms will be omitted as per your expectation.

I'm going to go ahead and close this since the constraints *are* in place and ParmEd is in this case behaving both as intended and as documented.

**Closed by swails** 2019-03-31 19:32 UTC
