### ISSUE TITLE
Issues with OpenMM nonbonded ffxml section writing with frcmod files

### ISSUE THREAD

**Issue by jchodera** [ParmEd/ParmEd#568] opened 2016-01-24 04:52 UTC
If we ask ParmEd to read a simple `frcmod` file like this
```
Remark line goes here
MASS

BOND

ANGLE

DIHE

IMPROPER
ca-ca-ca-ha         1.1          180.0         2.0          Using general improper torsional angle  X- X-ca-ha, penalty score=  6.0)

NONBON

```
and output an `ffxml` file, we get the following error:
```
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/choderaj/github/choderalab/openmoltools/openmoltools.jchodera/openmoltools/tests/test_forcefield_generators.py", line 118, in test_generateResidueTemplate
    [template, ffxml] = generateResidueTemplate(mol)
  File "/Users/choderaj/github/choderalab/openmoltools/openmoltools.jchodera/openmoltools/forcefield_generators.py", line 343, in generateResidueTemplate
    params.write(ffxml)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/openmm/parameters.py", line 153, in write
    self._write_omm_nonbonded(dest)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/parmed/openmm/parameters.py", line 358, in _write_omm_nonbonded
    coulomb14scale = 1.0 / scee.pop()
KeyError: 'pop from an empty set'
```
Example code:
```python
    # Generate ffxml file contents for parmchk-generated frcmod output.
    leaprc = StringIO("parm = loadamberparams %s" % frcmod_filename)
    params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)
    params = parmed.openmm.OpenMMParameterSet.from_parameterset(params)
    ffxml = StringIO()
    params.write(ffxml)
```

**Comment by jchodera** [comment] 2016-01-24 04:53
I think we will have to have the various parameter set reading routines set defaults common for the forcefield in case there are no torsions defined.

**Comment by swails** [comment] 2016-01-25 13:23
Ack.  This wasn't a use-case I had considered.  I wrote `from_parameterset` aimed at converting an entire parameter set rather than simply a small frcmod file.

I'll work on a fix for this.  Thanks.

**Comment by jchodera** [comment] 2016-01-25 13:32
We could certainly designate a"parent parameter set " (like gaff.dat) but
we would want to write only the new parameters from the ffxml.

**Comment by swails** [comment] 2016-01-25 13:39
I'd rather just implement expected behavior :).  This frcmod file really has no business trying to implement nonbonded parameters, anyway.  It should create an XML file with *just* the additional improper.

**Comment by jchodera** [comment] 2016-01-26 20:00
Any luck with this?

**Comment by swails** [comment] 2016-01-26 20:03
I'm thrashing around on #569 right now :frowning:.  CI is running now though, so I'll take a crack at this.

**Comment by swails** [comment] 2016-01-26 20:20
OK -- #570 should fix this.  Turned out to be a pretty easy fix, although I hopefully future-proofed it a little.  In reality, it shouldn't even have been trying to write a `<NonbondedForce>` generator here since it didn't define any new atom types!

I still added default SCEE/SCNB values (set for each class of FF according to typical defaults) when there are new atom types but no dihedrals which would define the scaling factors.  This should be less common, although certainly not impossible (and the default is typically fine, because the only way you can get away with having new atom types and not defining 1-4 scaling factors is if those new types are not involved in any torsions!)

**Comment by swails** [comment] 2016-01-26 20:39
OK, this should be fixed.

**Closed by swails** 2016-01-26 20:39 UTC
Labels: bug

**Comment by jchodera** [comment] 2016-01-26 21:23
Awesome, thanks!  Testing now in my `openmoltools` PR to implement GAFF forcefield generator plugins for OpenMM's `ForceField`: https://github.com/choderalab/openmoltools/pull/164
