### ISSUE TITLE
Potential bug of the distance criteria mask in ParmEd

### ISSUE THREAD

**Issue by pengfeili1** [ParmEd/ParmEd#850] opened 2017-03-17 20:35 UTC
Hi Jason,

There may be a bug in ParmEd about using distance criteria mask.

Pengfei

**Comment by hainm** [comment] 2017-03-17 20:50
> There may be a bug in ParmEd about using distance criteria mask.

detail detail :P

**Comment by pengfeili1** [comment] 2017-03-17 21:37
Hi Hai, I have sent an email to Jason, I will forward that email to you as well. Since it is about a system I am working on, I think it is better not to attach the files here.

**Comment by hainm** [comment] 2017-03-17 21:38
ah I see. no need to forward to me. You just need to say "what bug?" without attaching your file.

**Comment by pengfeili1** [comment] 2017-03-17 21:39
OK. It doesn't work with this command "strip (:1-842>:10.0)&:WAT,Na+,Cl- nobox" while ambmask works file.

**Comment by pengfeili1** [comment] 2017-03-17 21:40
I mean ambmask can recognize the mask well but ParmEd doesn't.

**Comment by hainm** [comment] 2017-03-17 21:42
Did you put "nobox" to ParmEd? Why do you need  this?

**Comment by swails** [comment] 2017-03-18 04:28
@pengfeili1 -- the files you sent me worked fine on the latest version of ParmEd.

It looks like the difference is that ambmask selects all atoms that are in a residue in which *all* atoms are >10 Angstroms away, and ParmEd just requires that *one* atom from the residue be at least 10 angstroms away.

The < semantics should be the same.

> I mean ambmask can recognize the mask well but ParmEd doesn't.

Can you elaborate on what this means?  Does ParmEd print out an error, or is it just that the selection sizes are different?

**Comment by swails** [comment] 2017-03-18 17:42
One thing I'll point out is that distance-based masks are *slow* to evaluate in ParmEd (since it has to do distance calculations in pure Python).  I should ideally numpy-vectorize the distance calcs (or JIT them with `numba`), but until then you may be better off with cpptraj for this kind of thing.

**Comment by pengfeili1** [comment] 2017-03-20 01:53
Hi Hai, Yeah, I put a “nobox” in my script. I am now doing QM/MM calculations, and the former protocol in our lab uses CHARMM, and I want to use AMBER now but also follow the former protocol as much as possible.

**Comment by pengfeili1** [comment] 2017-03-20 01:55
Hi Jason,

> On Mar 17, 2017, at 11:28 PM, Jason Swails <notifications@github.com> wrote:
> 
> @pengfeili1 <https://github.com/pengfeili1> -- the files you sent me worked fine on the latest version of ParmEd.
> 
> It looks like the difference is that ambmask selects all atoms that are in a residue in which all atoms are >10 Angstroms away, and ParmEd just requires that one atom from the residue be at least 10 angstroms away.
> 
> The < semantics should be the same.
> 
> I mean ambmask can recognize the mask well but ParmEd doesn't.
> 
> Can you elaborate on what this means? Does ParmEd print out an error, or is it just that the selection sizes are different?
> 
Not print out an error but the selection sizes are different, in my running, ParmEd recognize that command as striping out all the water molecules and ions.

**Comment by pengfeili1** [comment] 2017-03-20 02:08
Hi Jason, thanks for the advice. Cpptraj works much faster.

**Comment by swails** [comment] 2017-05-24 04:03
The behavior matches what is documented (even if it's slow), and I haven't been able to reproduce this.  Closing for now.

**Closed by swails** 2017-05-24 04:03 UTC
