### ISSUE TITLE
Convert Amber topology with nonstandard bonds to Gromacs format

### ISSUE THREAD

**Issue by nanobiophys** [ParmEd/ParmEd#759] opened 2016-09-20 22:36 UTC
Hi, thanks to Hai for inviting me to open an issue here. 

I have Amber topology files and trajectories to convert to Gromacs format for a program using gromacs.tpr and .trr as inputs. In my system, I created a pair of non-standard residues that form disulfide-like bonds between molecules. 
I tried cpptraj- it could not generate gromacs.top and .gro for this system; cpptraj gave a .trr trajectory, but Gromacs cannot read it (I tried trjconv and gmxdump).

Then I followed this to convert my topology: https://github.com/ParmEd/ParmEd/issues/631
It gave a gromacs.top and retains the non-standard bonding information. It rearranges blocks of residues (I now suppose) to set chains with the disulfide-like as a single molecule...so "X,Y,Z" becomes "XZ,Y" . 

But it does not rearrange the coordinate file in the same way, so I got mismatched atoms when I ran the gromacs-based program before I noticed it.

I saw a prior issue about re-ordering the topology: https://github.com/ParmEd/ParmEd/issues/469
but have not set out to do this as it isn't settled.

Any suggestion?

**Comment by hainm** [comment] 2016-09-20 22:37
> cpptraj gave a .trr trajectory, but Gromacs cannot read it (I tried trjconv and gmxdump).

which cpptraj version you are using? I think @droe has a fix for that.

**Comment by nanobiophys** [comment] 2016-09-20 22:40
I am using cpptraj V16.00. 
But the simulations were done by Amber14, and I did not use ParmEd to setMolecules before I ran the simulations.

**Comment by droe** [comment] 2016-09-20 22:46
@hainm I'm afraid that I have no idea what you're talking about, you must be mistaking me for someone else.

**Comment by hainm** [comment] 2016-09-20 22:50
@droe  I am sorry. Should be @drroe

**Comment by swails** [comment] 2016-09-21 01:02
@nanobiophys -- unfortunately Amber files that are *not* reordered (such that molecules appear contiguously in their atom order) are simply incorrect and corrupt Amber files.  The fact that ParmEd does this re-ordering for you is a feature, and a rather challenging one to do correctly (largely because most people aren't aware of it :smiley:).

If you have pre-existing trajectory files (either generated by Amber or GROMACS), you can use the ``fixatomorder`` command in cpptraj to write a new set of trajectory or coordinate files.  I believe that for non-pathological cases, cpptraj and ParmEd reorder atoms in exactly the same way.  So, for example, you can reorder a trajectory with cpptraj and then create a reordered topology with ParmEd and use them together.

You'll have to try this to be sure, though.

**Comment by drroe** [comment] 2016-09-21 12:36
> I am using cpptraj V16.00. 

@nanobiophys The TRR bug is not present in the current GitHub version (17b) or the current AmberTools 16 version (16.12). I recommend upgrading to one or the other.

**Comment by nanobiophys** [comment] 2016-09-21 19:58
@swails -- Thanks for the comments. I also have tried fixatomorder but did not get the re-ordered trajectory I expected. Now I see I did not use it correctly. 
Say the oldAmber.prmtop and oldAmber.mdcrd contain chains in the order "X,Y,Z" and a re-ordered ParmEd.prmtop contains "XZ,Y":
  >parm oldAmber.prmtop 
  >trajin oldAmber.mdcrd
  >fixatomorder

Then trajout gave me coordinates "X,Y,Z" with atom names in the order of "XZ,Y" (which is wrong).

With your message I tried again and realized from a discussion: http://archive.ambermd.org/201608/0470.html
that I might be using a wrong sequence of commands. So I did
  >parm oldAmber.prmtop 
  >fixatomorder
  >trajin oldAmber.mdcrd

And trajout gave me perfectly re-ordered "XZ,Y" coordinates which I can now use with the ParmEd.prmtop. I'm glad my system isn't too pathological. It might also help to stress that we should assign fixatomorder before we trajin the coordinates.

**Comment by drroe** [comment] 2016-09-22 00:14
@nanobiophys The two inputs your provided to cpptraj should be equivalent. Are you sure you were using the same input topology and trajectory for both runs?

**Comment by nanobiophys** [comment] 2016-09-22 20:30
@drroe Yes, I check the log file and am pretty sure I was using the exactly same input topology and trajectory for both runs.  But I find that I did trajout in the same way so I just try again.
With the input of my initial try
>parm oldAmber.prmtop 
>trajin oldAmber.mdcrd
>fixatomorder outprefix fixat
>trajout fixat.pdb

I trajout the coordinates to pdb format, but do not get the "XZ,Y" arrangement in them.
But with the input
>parm oldAmber.prmtop 
>trajin oldAmber.mdcrd
>fixatomorder outprefix fixat
>trajout fixat.mdcrd

Then I get fixat.mdcrd in the desired arrangement.  So your comment regarding input is true.  I have no idea why it does not work right doing trajout to pdb though.

**Comment by drroe** [comment] 2016-09-27 17:06
@nanobiophys I have been unable to reproduce your issue. If the files `oldAmber.prmtop` and `oldAmber.mdcrd` are not too large could you post them so I can try to reproduce your issue? If the trajectory is too big you could just send 1 frame. Thanks.

**Comment by nanobiophys** [comment] 2016-09-29 01:40
@drroe Thanks for looking into it.  I think the files are way big even if I only include one frame. Which address or destination would you like me to send them to?

**Comment by drroe** [comment] 2016-09-29 13:47
@nanobiophys you can send them to my gmail account: daniel.r.roe_at_gmail. Thanks.

**Comment by drroe** [comment] 2016-09-30 17:21
Thanks for the files. However, I could not reproduce your issue. Here is the script I used to check cpptraj:
```bash
#!/bin/bash
# Output to PDB
cat > test1.in <<EOF
parm oldAmber.prmtop
trajin oldAmber.inpcrd
fixatomorder outprefix fixat1
trajout fixat1.pdb
EOF
cpptraj -i test1.in
# Output to mdcrd
cat > test2.in <<EOF
parm oldAmber.prmtop
trajin oldAmber.inpcrd
fixatomorder outprefix fixat2
trajout fixat2.mdcrd
EOF
cpptraj -i test2.in
# Convert fixed PDB to mdcrd for comparison
cpptraj -p fixat1.oldAmber.prmtop -y fixat1.pdb -x fixat3.mdcrd
# Compare
diff fixat2.mdcrd fixat3.mdcrd | wc -l
```
Output is '0' indicating no difference between the files generated using PDB as output and mdcrd as output.

**Comment by nanobiophys** [comment] 2016-09-30 17:48
Thanks for the script.  Did you test it with the GitHub version (17b) or the AmberTools 16 version (16.12)?

**Comment by drroe** [comment] 2016-09-30 18:08
> Thanks for the script. Did you test it with the GitHub version (17b) or the AmberTools 16 version (16.12)?

Both. Latest version of AT cpptraj is actually 16.14.

**Comment by nanobiophys** [comment] 2016-09-30 18:11
I see, I have not tried upgrading yet.  Thank you.

**Comment by swails** [comment] 2016-12-05 00:04
@nanobiophys -- did this ever get resolved?

**Comment by nanobiophys** [comment] 2016-12-07 00:07
@swails I haven't succeeded installing newer version of cpptraj to test drroe's script, but my original issue has been resolved. Thanks for following.

**Comment by swails** [comment] 2016-12-07 00:23
Good to hear. I'm going to go ahead and close this, then.

**Closed by swails** 2016-12-07 00:23 UTC
